mackerelio/mackerel-agent-plugins

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Elasticsearch: add evictions, lucene segments memory size #58
=> Release version 0.6.3

mackerel-plugin-aws-elasticache/README.md, mackerel-plugin-aws-elasticache/aws-elasticache.go
note: memcached has actually used. But redis does not use.
=> A plugin for elasticache

.travis.yml, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
- A plugin for PHP OPcache #60
- Add a parameter to specify the LoadBalancerName #63
- A plugin for elasticache #64
- A plugin for AWS SES (Quota, Send Statistics) #65
- Elasticsearch: change "Indices Docs" to stacked graph #66
- jvm plugin -pidfile option jstat failed #68
- Fix some failed unit tests #69
=> Release version 0.7.0

mackerel-plugin-linux/linux.go
- Fix login user counter.
- Merge metrics: disk io time, read/write time.
=> Fix linux users, disk time metrics

mackerel-plugin-xentop/xentop.go
XenのDom0におけるxentopコマンドをサポートするプラグインです．  
現在以下のメトリクスを取得することができます．  
* CPU(%)  
100*CPUコア数を上限とした時のCPUの利用率を取得．  
* MEM(%)  
各DomUへのメモリの割り当て量の割合を取得．  
* NETTX(bytes)  
Network tx byte  
* NETRX(bytes)  
Network rx bytes  
* VBD_RD(IOPS)  
VBD Readリクエストの数．  
* VBD_WR(IOPS)  
VBD Writeリクエストの数．
よろしくお願いします．
=> mackerel-plugin-xentop

mackerel-plugin-nginx/nginx.go
I have changed the mackerel-plugin-nginx, to be able to set the any header at HTTP request.
=> nginx: Add a 'header' parameter to command-line flags

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- nginx: Add a 'header' parameter to command-line flags #78
- remove mackerel-agent dependency #79
=> Release version 0.8.1

mackerel-plugin-aws-rds/aws-rds.go
=> Add Throughput and Network Throughput metrics to AWS RDS Plugin

.travis.yml, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
- Fix elasticache plugin #81
- Add td-table-count plugin #83
- additional help for nginx SSL sites #84
- Add Throughput and Network Throughput metrics to AWS RDS Plugin #85
- Feature/haproxy basicauth #86
=> Release version 0.9.0

mackerel-plugin-varnish/varnish.go
When using ESI, `cache_hit`, `cache_miss`, and/or `cache_hitpass` might be counted more than once by one client request.  I think that using sum of `cache_hit`, `cache_miss`, and `cache_hitpass` as the number of requests is better than using `client_req`.
=> Fix an error in the number of requests of Varnish

packaging/config.json, tool/releng
Add packaging/config.json for packaging rpm and deb files.
By this config, we specify the plugins to be contained in rpm and deb.
=> add packaging/config.json

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Fix an error in the number of requests of Varnish #90
=> Release version 0.9.1

mackerel-plugin-mysql/mysql.go, mackerel-plugin-mysql/mysql_test.go
=> Mysql better error handling

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- elasticsearch: add memory size used by lucene segments, which were exposed in Elasticsearch 1.4 #92
- mysql: better error handling #94
=> Release version 0.9.2

mackerel-plugin-aws-cloudfront/README.md, mackerel-plugin-aws-cloudfront/aws-cloudfront.go
Add mackerel-plugin-aws-cloudfront.
This plugin get metrics of CloudFront from CloudWatch same as ELB.
=> Add mackerel-plugin-aws-cloudfront

mackerel-plugin-mysql/mysql.go
https://dev.mysql.com/doc/refman/5.5/en/server-status-variables.html#statvar_Threads_created
=> Fix mysql plugin typo

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- [nginx] specify types of nginx metrics #106
=> Release version 0.11.1

mackerel-plugin-mongodb/mongodb.go, mackerel-plugin-mongodb/mongodb_test.go
current mongodb plugin does not work with mongodb 2.4 or later.
This pull requests make the plugin works with mongodb 2.4, 2.6, and 3.0.
=> Fix/mongodb 2.4 or later

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Fix/mongodb 2.4 or later #108
=> Release version 0.11.2

mackerel-plugin-aws-ec2-ebs/README.md, mackerel-plugin-aws-ec2-ebs/aws-ec2-ebs.go
=> Plugin for AWS-EC2 EBS

tool/releng
* show diff and pull-request body before push
* abort script when GitHub API returns non success response.
=> [nit] Improve releng to avoid a mistakes

.travis.yml, README.md, packaging/config.json, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
=> Release version 0.12.0

mackerel-plugin-fluentd/README.md, mackerel-plugin-fluentd/fluentd.go, mackerel-plugin-fluentd/fluentd_test.go
This pull request add mackerel-plugin-fluentd, which monitors fluentd http://www.fluentd.org/ .
=> add mackerel-plugin-fluentd

mackerel-plugin-docker/README.md, mackerel-plugin-docker/docker.go, mackerel-plugin-docker/docker_test.go
a mackerel plugin for Docker https://www.docker.com/ .
=> add mackerel-plugin-docker

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- [docker] resolve cgroup path in systemd environment #118
=> Release version 0.13.1

mackerel-plugin-xentop/xentop.go
1. Use wildcard definition
* ex) `xentop.cpu.#.cpu`
* metric expression changed: `xentop.cpu.cpu_${XENNAME}` -> `xentop.cpu.${XENNAME}.cpu`
2. Normalize xen names
* replace all `.` of xen name to `_`
=> use wildcard definition & normalize xen names

README.md, mackerel-plugin-aws-elasticsearch/README.md, mackerel-plugin-aws-elasticsearch/aws-elasticsearch.go
Created plugin for AWS Elasticsearch Service.
I'm a beginner in mackerel plugin development. If there are anything strange, please let me know.
=> added plugin for AWS Elasticsearch Service

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- fix index bug in plugin-xentop #135
=> Release version 0.14.1

mackerel-plugin-jvm/jvm.go
NEW領域、OLD領域それぞれのヒープ使用率及び
CMS GCの場合のCMSInitiatingOccupancyFractionの取得
=> Get memory usage percentage and CMSInitiatingOccupancyFraction when CMS GC is running

mackerel-plugin-varnish/varnish.go
=> add graphs to varnish plugin

mackerel-plugin-squid/README.md, mackerel-plugin-squid/squid.go
- fix README
- add patterns so that can work with squid v3
=> Squid: work with squid v3

mackerel-plugin-murmur/README.md, mackerel-plugin-murmur/murmur.go
[Murmur](http://wiki.mumble.info/wiki/Running_Murmur) custom metrics plugin for mackerel.io agent.
```
$ go run mackerel-plugin-murmur/murmur.go -host 127.0.0.1
murmur.connections.con_cur	0	1449132341
murmur.connections.con_max	100	1449132341
```
=> Add mackerel-plugin-murmur

mackerel-plugin-solr/README.md, mackerel-plugin-solr/solr.go
A mackerel plugin for [Apache Solr](http://lucene.apache.org/solr/)
I'll implement some test code later. I'm sorry. @Songmu 
- host ... 192.168.33.10
- core ... core1
```
$ go run mackerel-plugin-solr/solr.go -host=192.168.33.10
solr.core1.segmentCount.core1_segmentCount    3       1448706470
solr.core1.sizeInBytes.core1_sizeInBytes      105116679       1448706470
solr.core1.timeouts.core1_timeouts_updatejson 0       1448706470
solr.core1.timeouts.core1_timeouts_select     0       1448706470
solr.core1.timeouts.core1_timeouts_updatejsondocs     0       1448706470
solr.core1.timeouts.core1_timeouts_get        0       1448706470
solr.core1.timeouts.core1_timeouts_updatecsv  0       1448706470
solr.core1.timeouts.core1_timeouts_replication        0       1448706470 …
```
=> Add mackerel-plugin-solr

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- use mackerel-plugin-helper for mackerel-plugin-linux #159
=> Release version 0.15.1

packaging/config.json, packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
Add unicorn plugin to deb and RPM package
=> add unicorn plugin to package

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- add unicorn plugin to package #162
=> Release version 0.15.2

README.md, mackerel-plugin-inode/README.md, mackerel-plugin-inode/inode.go, packaging/config.json, packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
This pull request introduces a new plugin, inode plugin. This plugin generates two graphs, the number of used/free/total inodes, and the percentage of used inodes against the number of total inodes.
=> Add inode plugin

mackerel-plugin-jvm/jvm.go
To execute jps, jstat, jinfo...
=> [jvm] Add confirmation to error message

mackerel-plugin-elasticsearch/README.md, mackerel-plugin-elasticsearch/elasticsearch.go
Add scheme option to Elasticsearch plugin. We use Elasticsearch with ssl.
=> Add scheme option to Elasticsearch plugin

.travis.yml, README.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Add couple of metrics to Elasticsearch plugin #166
- [jvm] Add confirmation to error message #168
- Add scheme option to Elasticsearch plugin #169
- Add inode plugin #170
=> Release version 0.16.0

mackerel-plugin-memcached/README.md, mackerel-plugin-memcached/memcached.go
=> [memcached] support unix socket

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Fix helper.Tempfile in mysql.go #191
=> Release version 0.18.1

mackerel-plugin-mailq/README.md, mackerel-plugin-mailq/fixtures/postqueue, mackerel-plugin-mailq/fixtures/qmail/qmail-qstat, mackerel-plugin-mailq/main.go, mackerel-plugin-mailq/main_test.go
I would like the standard plugin set to have a command to take the mail queue metrics.
=> Add mailq plugin

mackerel-plugin-gearmand/README.md, mackerel-plugin-gearmand/gearmand.go, mackerel-plugin-gearmand/gearmand_test.go
Gearmand custom metrics plugin for mackerel.io agent.
=> added mackerel-plugin-gearmand

packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
use `/usr/bin/mackerel-plugin-*`, and put symlinks into `/usr/local/bin/mackerel-plugin-*` (old only)
=> use /usr/bin/mackerel-plugin-*

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- use /usr/bin/mackerel-plugin-* #201
- use GOARCH=amd64 for now #203
=> Release version 0.19.1

packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
Reverts mackerelio/mackerel-agent-plugins#201
=> Revert "use /usr/bin/mackerel-plugin-*"

.travis.yml, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Revert "use /usr/bin/mackerel-plugin-*" #205
=> Release version 0.19.2

packaging/deb/debian/rules, packaging/rpm/mackerel-agent-plugins.spec
Reverts mackerelio/mackerel-agent-plugins#205
=> Revert "Revert "use /usr/bin/mackerel-plugin-*""

Makefile, mackerel-plugin-nginx/nginx.go
fix typo  "wating" -> "waiting"
=> [nginx] fix typo

mackerel-plugin-proc-fd/README.md, mackerel-plugin-proc-fd/open_fd.go, mackerel-plugin-proc-fd/proc_fd.go, mackerel-plugin-proc-fd/proc_fd_test.go
This plugin monitor opening file descriptor.
=> Add mackerel plugin proc fd

mackerel-plugin-graphite/README.md, mackerel-plugin-graphite/cache_meta.go, mackerel-plugin-graphite/graphite.go, mackerel-plugin-graphite/graphite_test.go, mackerel-plugin-graphite/meta.go, mackerel-plugin-graphite/metrics.go, mackerel-plugin-graphite/metrics_test.go, mackerel-plugin-graphite/relay_meta.go
This is graphite carbon custom metrics plugin.
Now README.md is not enough, so I will update soon.
=> Add mackerel-plugin-graphite

mackerel-plugin-docker/docker.go
If there are many docker containers, timeout occurs while fetching metrics, because mackerel-plugin-docker fetches metrics of each container sequentially.
To shorten the time, use goroutine.
- 18 containers (note: following number include header line.)
```
% docker ps | wc -l
19
```
- current version takes over 30 seconds.
```
% time /usr/local/bin/mackerel-plugin-docker -tempfile=/tmp/aa -method API > /dev/null
/usr/local/bin/mackerel-plugin-docker -tempfile=/tmp/aa -method API  0.02s user 0.02s system 0% cpu 35.754 total
```
- gorouttine version takes around 6 seconds.
```
% time ./mackerel-plugin-docker -tempfile=/tmp/aa -method API > /dev/null
./mackerel-plugin-docker -tempfile=/tmp/aa -method API > /dev/null  0.01s user 0.02s system 0% cpu 5.706 total
```
=> [docker] use goroutine for fetching metrics via API

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- [docker] use goroutine for fetching metrics via API #220
- add graphite and proc-fd into package #223
=> Release version 0.20.0

mackerel-plugin-apache2/apache2.go, mackerel-plugin-linux/linux.go, mackerel-plugin-php-apc/php-apc.go, mackerel-plugin-php-opcache/php-opcache.go
interface changed at https://github.com/codegangsta/cli/pull/361
=> change signatures of doMain to follow recent codegangsta/cli

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- change signatures of doMain to follow recent codegangsta/cli #227
- fix README.md of mackerel-plugin-jvm #228
=> Release version 0.20.1

mackerel-plugin-aws-ec2-ebs/aws-ec2-ebs.go
This pull request changes the metric keys and graph keys of the aws-ec2-ebs plugin. The original code creates each metric per EBS volume, creates hundreds and thousands of metrics in an organization.
ref: #110
=> aws-ec2-ebs: Use wildcard in the graph definitions

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- aws-ec2-ebs: Use wildcard in the graph definitions #230
=> Release version 0.20.2

mackerel-plugin-redis/README.md, mackerel-plugin-redis/redis.go
Like this:
```shell
$ mackerel-plugion-redis -password=password
```
=> Support password authentication of Redis

mackerel-plugin-fluentd/README.md, mackerel-plugin-fluentd/fluentd.go, mackerel-plugin-fluentd/fluentd_test.go
Add an option to specify type and id pattern because I want to post the necessary metric only.
=> Add an option to specify type and id pattern to fluentd plugin

mackerel-plugin-fluentd/fluentd.go, mackerel-plugin-fluentd/fluentd_test.go
=> [nit] Adjust mackerel plugin fluentd

mackerel-plugin-php-fpm/php-fpm.go
Fix wrong help message for `url` option.
=> Fix help message

README.md
Add links for graphite, php-fpm and proc-fd.
=> Add some plugins to README

mackerel-plugin-mysql/mysql.go
`MySQLPlugin` now implements `mp.PluginWithPrefix` interface.
=> [mysql] support -metric-key-prefix option

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Fix help message #244
- [apache2] update README.md. fix mod_status configuration #245
- Add some plugins to README #247
- follow urfave/cli #249
- [mysql] support -metric-key-prefix option #250
=> Release version 0.21.2

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
=> Release version 0.22.0

mackerel-plugin-memcached/README.md, mackerel-plugin-memcached/memcached.go
There're some plugins already supporting this option(mysql, redis, ...).
=> [memcached] Support -metric-key-prefix option 

mackerel-plugin-docker/README.md, mackerel-plugin-docker/docker.go, mackerel-plugin-graphite/graphite.go, mackerel-plugin-haproxy/haproxy.go, mackerel-plugin-mysql/mysql.go, mackerel-plugin-mysql/mysql_test.go
I fixed some warnings detected by Go Report Card.
=> [nit] Refine code style

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Fixed README.md #253
- [memcached] Support -metric-key-prefix option  #255
=> Release version 0.22.1

mackerel-plugin-elasticsearch/elasticsearch.go
add open file descriptors metric.
i want this graph.
=> [elasticsearch] Add open_file_descriptors metric in elasticsearch plugin

mackerel-plugin-elasticsearch/elasticsearch.go
=> fix: "open file descriptors" property in elasticsearch 

mackerel-plugin-memcached/memcached.go
elasticache memcached support it.
https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/CacheMetrics.Memcached.html
=> [memcached] support new_items metrics

mackerel-plugin-redis/redis.go
I made a typo :innocent: https://github.com/mackerelio/mackerel-agent-plugins/pull/269/files#diff-4b78c4735dfe237f16d9d8d5c5de90a3R60
=> [redis] s/memoty/memory/

mackerel-plugin-redis/redis_test.go
- This branch should pass ci
- This additional tests fails without #277 
- You can confirm by following:
```
$ cd mackerel-pugin-redis
$ git checkout 18604d2e2956d673c0e278a2653b127ab25c0aeb -- redis..go
$ go test
--- FAIL: TestFetchMetricsPercentageOfMemory (0.11s)
panic: interface conversion: interface is nil, not float64 [recovered]
panic: interface conversion: interface is nil, not float64
goroutine 20 [running]:
panic(0x1767a0, 0xc420011b00)
/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008a240)
/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:579 +0x25d
panic(0x1767a0, 0xc420011b00)
/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
_/Users/asato/.ghq/github.com/mackerelio/mackerel-agent-plugins/mackerel-plugin- …
```
=> [nit] [redis] Add tests for #277

mackerel-plugin-jvm/README.md
In many case, Monitoring target java process is not executed by root. So I'd like add some information to README.
=> [jvm] Add notice about user to README

packaging/config.json
Adds mackerel-plugin-twemproxy to the package.
=> Add mackerel-plugin-twemproxy to package

mackerel-plugin-apache2/lib/apache2.go
=> [apache2] fix typo in graphdef

mackerel-plugin-docker/lib/docker.go
`Timeout: 0` means it waits forever: https://github.com/fsouza/go-dockerclient/blob/master/client.go#L565-L568
=> [docker] Add timeout for API request

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
- Make more plugins to support MACKEREL_PLUGIN_WORKDIR #301 (astj)
- Fix the label and scale in jvm plugin #302 (itchyny)
- [aws-rds] Make it possible to get normal value from all engine. #303 (sioncojp)
=> Release version 0.25.1

mackerel-plugin-aws-rds/lib/metrics.go
=> [aws-rds] fix metric name

mackerel-plugin-multicore/lib/multicore.go
tempfile was not created in multicore plugin.
=> [multicore]fix tempfile path

mackerel-plugin-gcp-compute-engine/README.md, mackerel-plugin-gcp-compute-engine/lib/gcp-compute-engine.go
ref: #304
Thanks to littlekbt, but we need some improvements.
- Make `-project` and `-instance-name` specifiable from command line params
- Improve error handling and logging
=> Improve gce plugin

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-agent-plugins.spec
=> Release version 0.25.4

mackerel-plugin-aws-waf/README.md, mackerel-plugin-aws-waf/lib/aws-waf.go, mackerel-plugin-aws-waf/main.go
=> Add AWS WAF Plugin

mackerel-plugin-gostats/lib/mackerel-plugin-gostats.go
=> fix a label of gostats plugin

mackerel-plugin-aws-rekognition/README.md, mackerel-plugin-aws-rekognition/lib/aws-rekognition.go, mackerel-plugin-aws-rekognition/main.go
I created AWS Rekognition Plugin.
=> Add AWS Rekognition Plugin

mackerel-plugin-aws-kinesis-streams/README.md, mackerel-plugin-aws-kinesis-streams/lib/aws-kinesis-streams.go, mackerel-plugin-aws-kinesis-streams/lib/aws-kinesis-streams_test.go, mackerel-plugin-aws-kinesis-streams/main.go
ref: http://docs.aws.amazon.com/streams/latest/dev/monitoring-with-cloudwatch.html
Original implementation is https://github.com/astj/mackerel-plugin-aws-kinesis-streams .
=> Add aws-kinesis-streams plugin

mackerel-plugin-aws-lambda/README.md, mackerel-plugin-aws-lambda/lib/aws-lambda.go, mackerel-plugin-aws-lambda/lib/aws-lambda_test.go, mackerel-plugin-aws-lambda/main.go
Original: https://github.com/astj/mackerel-plugin-aws-lambda
=> Add AWS Lambda plugin

mackerel-plugin-redis/lib/redis.go
fix typo "Blocked Clients" → "Connected Slaves"
=> [redis] fix metrics lable

mackerel-plugin_gen.go, packaging/config.json
=> Add aws-lambda and aws-kinesis-streams to package

mackerel-plugin_gen.go, packaging/config.json
Add https://github.com/mackerelio/mackerel-agent-plugins/pull/335 to package.
=> add mackerel-plugin-uwsgi-vassal to package

mackerel-plugin-aws-cloudfront/lib/aws-cloudfront.go, mackerel-plugin-aws-ec2-cpucredit/lib/aws-ec2-cpucredit.go, mackerel-plugin-aws-ec2/lib/aws-ec2.go, mackerel-plugin-aws-elasticache/lib/aws-elasticache.go, mackerel-plugin-aws-elasticsearch/lib/aws-elasticsearch.go, mackerel-plugin-aws-elb/lib/aws-elb.go, mackerel-plugin-aws-rds/lib/aws-rds.go, mackerel-plugin-aws-ses/lib/aws-ses.go, mackerel-plugin-docker/lib/docker.go, mackerel-plugin-elasticsearch/lib/elasticsearch.go, mackerel-plugin-haproxy/lib/haproxy.go, mackerel-plugin-jvm/lib/jvm.go, mackerel-plugin-mongodb/lib/mongodb.go, mackerel-plugin-multicore/lib/multicore.go, mackerel-plugin-munin/lib/munin.go, mackerel-plugin-murmur/lib/murmur.go, mackerel-plugin-php-apc/lib/php-apc.go, mackerel-plugin-php-opcache/lib/php-opcache.go, mackerel-plugin-plack/lib/plack.go, mackerel-plugin-proc-fd/lib/proc_fd.go, mackerel-plugin-rabbitmq/lib/rabbitmq.go, mackerel-plugin-redis/lib/redis.go, mackerel-plugin-snmp/lib/snmp.go, mackerel-plugin-solr/lib/solr.go, mackerel-plugin-squid/lib/squid.go, mackerel-plugin-td-table-count/lib/mackerel-plugin-td-table-count.go, mackerel-plugin-trafficserver/lib/trafficserver.go, mackerel-plugin-unicorn/lib/unicorn.go, mackerel-plugin-varnish/lib/varnish.go, mackerel-plugin-xentop/lib/xentop.go
For most plugins there're no reason not to use `helper.Run()`.
https://github.com/mackerelio/go-mackerel-plugin-helper/blob/master/mackerel-plugin.go#L304-L311
=> [nit] Use helper.Run()

README.md
Same as https://github.com/mackerelio/go-check-plugins/pull/173
- Remove "CentOS 5" / "Debian 6"
- Add links to setup package repositories
=> Refine installation instruction

mackerel-plugin-aws-kinesis-firehose/README.md, mackerel-plugin-aws-kinesis-firehose/lib/aws-kinesis-firehose.go, mackerel-plugin-aws-kinesis-firehose/main.go
I created AWS Kinesis Firehose Plugin.
=> Add AWS Kinesis Firehose Plugin

.travis.yml, Makefile, packaging/rpm/mackerel-agent-plugins.spec
Adjust Makefile not to build the same file more than once.
=> Shorten build

mackerel-plugin-aws-dynamodb/README.md, mackerel-plugin-aws-dynamodb/lib/aws-dynamo-db.go, mackerel-plugin-aws-dynamodb/main.go
ref: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/dynamo-metricscollected.html
Original implementation: https://github.com/astj/mackerel-plugin-aws-dynamodb
=> Add aws-dynamodb plugin

mackerel-plugin-windows-process-stats/lib/process-stats_windows.go
ref. https://github.com/mackerelio/mackerel-agent-plugins/pull/364#discussion_r125425167
=> [nit] fix `-metric-key-prefix` flag

mackerel-plugin-windows-process-stats/README.md, mackerel-plugin-windows-process-stats/lib/process-stats_other.go
- fix the command option name
- fix typo in error message
=> fix mackerel-plugin-windows-process-stats

mackerel-plugin-mysql/README.md, mackerel-plugin-mysql/lib/mysql.go
Hello.
I want to even up mysql prefixes `Mysql foo` and `mysql.bar`.
What do you think?
I'm sorry I've not know how to test.
So I've not checked deeply.
=> Mysql prefix

mackerel-plugin-accesslog/lib/accesslog_test.go
ref. https://github.com/montanaflynn/stats/pull/32
=> fix testcase (Percentile logic is Fixed up)

tool/cpanfile
ref: https://github.com/mackerelio/Mackerel-ReleaseUtils/pull/2
=> Update Mackerel::ReleaseUtils to check git workspace is clean

mackerel-plugin-mysql/lib/mysql.go, mackerel-plugin-mysql/lib/mysql_test.go
add `handlers` and `transaction handler` graphs to ExtendedGraphs
=> [mysql]add handler graphs

mackerel-plugin-openldap/lib/openldap.go, mackerel-plugin-openldap/lib/openldap_test.go
* fix get latestCSN  (Value could not be acquired correctly.)
* fix unit of time
=> [OpenLDAP] fix get latestCSN

mackerel-plugin-unicorn/README.md, mackerel-plugin-unicorn/lib/unicorn.go
=> [unicorn] Support metric-key-prefix

mackerel-plugin-mysql/lib/mysql.go, mackerel-plugin-mysql/lib/mysql_test.go
Old InnoDB Plugin returns counter value as high/low 32bit.
=> [mysql]Fix makeBigint calculation

mackerel-plugin-php-fpm/lib/php-fpm.go, mackerel-plugin-redis/lib/redis.go, mackerel-plugin-uptime/lib/uptime.go
=> [nit] fix typo Faild to Failed

LICENSE, README.md
@Songmu Review this pull request, please.
Fixes #447
=> Fix license notice

mackerel-plugin-json/lib/json.go
- Do error handling
- Exits when `-url` is not specified
=> [json] Fix error handling

mackerel-plugin-linux/README.md
I edited README.md of mackerel-plugin-linux
- Delete type = "metric"
- Changing installed path
=> Changed README.md of mackerel-plugin-linux

mackerel-plugin-redis/lib/redis.go
Offset delay and lag are replication stats for redis between master and slave. This PR adds `redis.offset_delay.slave{n}_offset_delay`, `redis.lag.slave{n}_lag` metrics, by the following Redis response:
```
echo -e "INFO REPLICATION\r\nQUIT\n" | nc 127.0.0.1 6379
...
slave0:ip=0.0.0.0,port=6379,state=online,offset=7500000000000,lag=0
slave1:ip=0.0.0.0,port=6379,state=online,offset=7500000000000,lag=0
...
=> [redis] Add Redis replication delay and lag metrics

mackerel-plugin-mysql/lib/mysql.go
I'd like to fix mackerel-agent-plugin-mysql, but value receiver is difficult to handle.
In begin with, change value receiver to pointer receiver for fixing plugin.
=> MySQL Plugin change value receiver to pointer receiver

mackerel-plugin-apache2/lib/apache2.go, mackerel-plugin-php-apc/lib/php-apc.go, mackerel-plugin-php-opcache/lib/php-opcache.go
a present position, If StatusCode is not StatusOK then the response body do not close.
=> add defer to closing the response body, and change position it.

mackerel-plugin-mysql/lib/mysql.go
=> [mysql] Fix message for socket option

mackerel-plugin-haproxy/lib/haproxy.go
=> [haproxy]support unix domain socket

mackerel-plugin-mongodb/lib/mongodb.go
=> [mongodb] fix connections_current metric mongodb-Replica-Set

mackerel-plugin-mongodb/lib/mongodb.go, mackerel-plugin-mongodb/lib/mongodb_docker_test.go
- WARNING will be displayed with mongodb > 3.2
=> [mongodb] Fix warning message on MongoDB 3.4, 3.6

mackerel-plugin-jvm/lib/jvm.go
ref: https://github.com/Songmu/timeout/pull/17
=> [nit] [jvm] Follow changes of github.com/Songmu/timeout

mackerel-plugin-redis/lib/redis.go, mackerel-plugin-redis/lib/redis_test.go
I would like to monitor Redis uptime.
=> [Redis] send uptime

.travis.yml, mackerel-plugin-flume/lib/flume.go, mackerel-plugin-redash/lib/redash_test.go
And also I applied `gofmt -w` to source files.
=> Build with Go 1.11

mackerel-plugin-postgres/lib/postgres.go
My development env of Postgres doesn't need to specify a password. It would be great if without check it.
=> [postgres] Enable connection without password

mackerel-plugin-squid/lib/squid.go, mackerel-plugin-squid/lib/squid_test.go
=> [squid] Add metrics to squid

mackerel-plugin-redis/lib/redis.go
IMHO, these lines became unnecessary after #537.
=> [redis] remove unnecessary code

mackerel-plugin-jvm/lib/jvm.go, mackerel-plugin-jvm/lib/jvm_test.go, mackerel-plugin-jvm/lib/testdata/jstat_serialgc.sh
I fixed #556
Also CGC and CGCT are not defined in graph defs. So I added them.
**C** at the first character of CGC and CGCT means concurrent. Therefore CGC is number of concurrent garbage collection, like as YGC.
https://stackoverflow.com/questions/55803602/whats-the-meaning-of-cgc-and-cgct-in-jdk11-jstat-gc-pid
=>  [plugin-jvm] added CGC and CGCT metrics and fixed parsing problem on them

.travis.yml
Fixes builds continue failing
ref: https://github.com/mackerelio/mkr/pull/211
=> add fakeroot to build dependencies

mackerel-plugin-sidekiq/README.md, mackerel-plugin-sidekiq/lib/sidekiq.go
closes #563
rebased to fix the build 
related to #564
=> [sidekiq] add option for redis-namespace

mackerel-plugin-jvm/README.md
Hi,
Added mentioning the PerfDisableSharedMem JVM option related #568 to README.
=> [jvm] Add the PerfDisableSharedMem JVM option issue to README

README.md
I added two links to refer repository policy.
=> [doc]add repository policy

mackerel-plugin-postgres/UPDATE.md, mackerel-plugin-postgres/test.sh
I added basic tests for mackerel-plugin-postgres.
=> [plugin-postgres] add test.sh

mackerel-plugin-redis/test.sh
I added basic tests for mackerel-plugin-redis.
ref #654
=> [plugin-redis] add test.sh

mackerel-plugin-aws-ses/lib/aws-ses.go, mackerel-plugin-aws-ses/lib/aws-ses_test.go
=> fix incorrect endpoint inspect condition

.github/workflows/test.yml
change to one with appropriate privileges
=> replace token

.github/workflows/test.yml, go.mod
=> upgrade Go 1.14 -> 1.16

mackerel-plugin-mysql/UPDATE.md, mackerel-plugin-mysql/lib/mysql.go, mackerel-plugin-mysql/lib/mysql_test.go, mackerel-plugin-mysql/test.sh
=> [plugin-mysql] Ignores non-numerical values

mackerel-plugin-aws-cloudfront/lib/aws-cloudfront.go, mackerel-plugin-aws-cloudfront/lib/aws-cloudfront_test.go
Replace label name of graph like this.
https://github.com/mackerelio/mackerel-agent-plugins/blob/df9c8643da21869d54cf8625dd7523d88b1c4e20/mackerel-plugin-aws-dynamodb/lib/aws-dynamo-db.go#L315
=> [plugin-aws-cloudfront]Replace label name of graph

go.mod, go.sum
ref: https://github.com/mackerelio/go-mackerel-plugin/pull/29 https://github.com/mackerelio/go-mackerel-plugin-helper/pull/44
=> bump go-mackerel-plugin and go-mackerel-plugin-helper

mackerel-plugin-fluentd/rule-workers.txt, mackerel-plugin-fluentd/test.sh, mackerel-plugin-fluentd/testdata/fluentd-workers.conf
I added **plugin-fluentd/test.sh** and related files.
=> [ci][fluentd] add test.sh

.github/workflows/create-release-pr.yml
this is for release flow tests.
=> replace token.

mackerel-plugin-docker/README.md, mackerel-plugin-docker/lib/docker.go
=> [plugin-docker] update README and a description of -command option

mackerel-plugin-uptime/lib/uptime_test.go
Add mackerel-plugin-uptime/lib/uptime_test.go
=> [uptime] Add tests

mackerel-plugin-aws-rds/README.md
I fixed typo in aws rds's document.
=> fix syntax for aws rds

.github/workflows/test.yml, .golangci.yml, mackerel-plugin-twemproxy/lib/twemproxy_test.go
- increase timeout to 5min for preparing golangci-lint
- use our reusable workflows
- upgrade Go toolchain to v1.20
- upgrade setup-go to v4
- twemproxy: avoid race conditions
=> [ci] refactor .github/workflows/test.yml

.github/workflows/test.yml, go.mod, go.sum
=> use Go 1.24

Makefile
when merge master, failed build debian package. because missing tarball.
fix it determine tarball filename from change log.
=> fix tarball version

.github/dependabot.yml
=> grouping some libraries

.github/dependabot.yml, .github/workflows/create-release-pr.yml, .github/workflows/test.yml
=> added dependabot cooldown
