mackerelio/mackerel-agent-plugins

mackerel-plugin-jvm/jvm.go

```
pid, err := ioutil.ReadFile(*optPidFile)
// pid : 20745\n
// pid_length : 6
```
use ReadFile case, pid contain "\n".
it replace to "" -> succeeded

jvm plugin -pidfile option jstat failed

---

mackerel-plugin-apache2/apache2.go
mackerel-plugin-apache2/apache2_test.go
mackerel-plugin-apache2/flags.go

I have changed the mackerel-plugin-apache2, to be able to set the any header at HTTP request.

apache2: Add a 'header' parameter to cli flags

---

mackerel-plugin-td-table-count/README.md
mackerel-plugin-td-table-count/mackerel-plugin-td-table-count.go

I'm afraid, I didn't write its tests.
Here is the output of this plugin.
```
./mackerel-plugin-td-table-count  -api-key="APIKEY" -database=DATABASE
td-table.[DATABASE].[TABLE]	122398	1429198003
td-table.[DATABASE].[TABLE]	105620	1429198003
td-table.[DATABASE].[TABLE]	216821	1429198003
td-table.[DATABASE].[TABLE]	127983	1429198003
td-table.[DATABASE].[TABLE]	187870	1429198003
td-table.[DATABASE].[TABLE]	21901	1429198003
td-table.[DATABASE].[TABLE]	23555	1429198003
td-table.[DATABASE].[TABLE]	23765	1429198003
td-table.[DATABASE].[TABLE]	12597	1429198003
```

Add td-table-count plugin

---

mackerel-plugin-nginx/README.md

If "scheme" flag is working, which I think is, it should be mentioned in the readme.  Users may end up only setting the port and give up.

additional help for nginx SSL sites

---

mackerel-plugin-postgres/README.md
mackerel-plugin-postgres/postgres.go

lib/pq uses username for database name when connect to database if database name does not specify.
So mackerel-plugin-postgres cannnot connect to database  if Postgresql does not has a database with the same name as the user name, As the following error.
```
$ /usr/local/bin/mackerel-plugin-postgres -password=*** -user=+++++
2015/06/25 16:04:30 ERROR <metrics.plugin.postgres> Failed to select pg_stat_database. pq: database "+++++" does not exist
2015/06/25 16:04:30 OutputValues:  pq: database "+++++" does not exist
```
I added a argument option for specfy database, then this plugin became able to connect a database.
thanks

Can specify database name option when postgresql does not has a database with the same name as the user name.

---

.travis.yml
README.md
packaging/config.json
packaging/deb/debian/changelog
packaging/deb/debian/rules
packaging/rpm/mackerel-agent-plugins.spec

- Can specify database name option when postgresql does not has a database with the same name as the user name. #97
- Add mackerel-plugin-aws-cloudfront #98

Release version 0.10.0

---

mackerel-plugin-redis/README.md

This is a tiny fix for README.md of Redis plugin. According to following line, you write `-host` option. However you write `-hostname` in README.md. `-host` is correct description.
https://github.com/mackerelio/mackerel-agent-plugins/blob/master/mackerel-plugin-redis/redis.go#L152

fix tiny typo

---

mackerel-plugin-redis/README.md
mackerel-plugin-redis/redis.go

If multiple Redis instances run on one server, we want to watch all status of them.
By using `-multi` option, port number is added to graph names and labels.
Redis runs as single process and single thread architecture.
If a server has many cores, I think, running multiple instances is an efficient way.

redis: add port to graph names for using multiple instances on one server

---

mackerel-plugin-memcached/memcached.go
mackerel-plugin-memcached/memcached_test.go
mackerel-plugin-mysql/mysql.go
mackerel-plugin-nginx/nginx.go
mackerel-plugin-nginx/nginx_test.go
mackerel-plugin-plack/plack.go
mackerel-plugin-plack/plack_test.go

The new helper https://github.com/mackerelio/go-mackerel-plugin-helper works well with uint64 counter especially in the case of counter overflow and counter reset.
With this pull request, plugins prevent to post a negative value for uint64 counter,

use new helper

---

.travis.yml
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- [redis] support multiple redis instances on one server by using -metric-key-prefix option #96
- [Redis] fix tiny documentation typo #101
- [memcached/mysql/nginx/plack] care counter overflow and reset by using new helper. #102
- [MySQL] Fix typo of metric name s/Thread_created/Threads_created/ #103
- [Redis] Support -socket option to specify unix socket #104

Release version 0.11.0

---

mackerel-plugin-aws-cloudfront/README.md
mackerel-plugin-aws-ec2-cpucredit/README.md
mackerel-plugin-aws-elb/README.md
mackerel-plugin-aws-rds/README.md
mackerel-plugin-aws-ses/README.md

I found unnecessary `=` of `secret-access-key==` in aws-* plugin's README.
I removed those `=` by the following.
```sh
$ pt -l --nogroup --nocolor "==<" | xargs sed -i '' 's/==</=</g'
```

[AWS-*] Fix typo s/secret-access-key==/secret-access-key=/

---

mackerel-plugin-fluentd/fluentd.go
mackerel-plugin-fluentd/fluentd_test.go

The value of fluentd config is not always string. So I remove `Config` field from FluentPluginMetrics. This plugin works without `Config` field.
```javascript
"config": {
"@type": "buffered_slack",
"@id": "twitter_slack_output",
"webhook_url": "https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxx",
"channel": "mackerel_social",
"message": "%s: %s https://twitter.com/%s/status/%s",
"message_keys": "user_screen_name,text,user_screen_name,id_str",
"flush_interval": "1m",
"time_format": "%H:%M:%S",
"localtime": true, // <- here!
},
```
```
$ mackerel-plugin-fluentd
2015/10/05 01:13:47 OutputValues:  json: cannot unmarshal bool into Go value of type string
```

remove Config field from FluentPluginMetrics

---

mackerel-plugin-docker/docker.go

In Amazon Linux, the path of cgroups statistics should be `/cgroup`, and some blkio metrics do not exist.
In CoreOS, some blkio metrics are also missing.
This pull request add a path candidate for Amazon Linux and error handling of missing metrics.

support coreos and amazon linux for docker plugin

---

mackerel-plugin-aws-rds/README.md
mackerel-plugin-aws-rds/aws-rds.go

With `-metric-key-prefix` option, metric key prefix can be changed. The default value of key prefix is `rds`.
And `-metric-label-prefix` can be specified for label prefix.
Without `-metric-label-prefix`, `RDS` is used for key prefix `rds` or capitalized key prefix is used for other key prefix.
- Key: `<metric-key-prefix>.Latency.ReadLatency`
- Label: `<metric-label-prefix> Latency in second`

Add Key prefix option for AWS RDS plugin

---

.travis.yml
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- reduce binary size #120
- remove Config field from FluentPluginMetrics #121
- support coreos and amazon linux for docker plugin #122
- Add Key prefix option for AWS RDS plugin #124

Release version 0.13.2

---

mackerel-plugin-jvm/jvm.go

add graph definition for java8 metaspace
(I want to display only either 'metaspace' or 'permanent space'. but I have no idea.)

add graph definition for java8 metaspace

---

.travis.yml
README.md
packaging/deb/debian/changelog
packaging/deb/debian/rules
packaging/rpm/mackerel-agent-plugins.spec

- Apache Traffic Server Plugin #126
- added plugin for AWS Elasticsearch Service #127
- use wildcard definition & normalize xen names #128
- add graph definition for java8 metaspace #129
- add plugins (aws-elasticsearch and trafficserver) into package #132

Release version 0.14.0

---

.travis.yml
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- Fix document #137
- Get memory usage percentage and CMSInitiatingOccupancyFraction when CMS GC is running #138
- follow latest aws-sdk-go #139

Release version 0.14.2

---

mackerel-plugin-memcached/memcached_test.go

`len(graphdef)` should be **8**.

Fix error message (typo)

---

mackerel-plugin-mysql/mysql.go

mackerel-plugin-mysql use https://github.com/ziutek/mymysql.
row.Int method is "Get the nn-th value and return it as int (0 if NULL). Panic if conversion is".
It can’t tell the difference between "Seconds_Behind_Master=NULL" and "Seconds_Behind_Master=0".
When Seconds_Behind_Master is NULL, agent-plugin doesn't send the Seconds_Behind_Master metric.

When Seconds_Behind_Master is NULL, agent-plugin doesn't send the Seconds_Behind_Master metric.

---

mackerel-plugin-elasticsearch/README.md
mackerel-plugin-elasticsearch/elasticsearch.go
mackerel-plugin-elasticsearch/elasticsearch_test.go

Add metric key and label prefix option to Elasticsearch plugin.
This enables us to get metrics from multiple Elasticsearch servers which cannot run mackerel-agent (e.g. hosted Elasticsearch services).

Add metric key and label prefix option to Elasticsearch plugin

---

.travis.yml
README.md
packaging/deb/debian/changelog
packaging/deb/debian/rules
packaging/rpm/mackerel-agent-plugins.spec

- Add mackerel-plugin-rabbitmq #165
- Add metric key and label prefix option to Elasticsearch plugin #173
- Add jmx jolokia plugin #174
- Add nf(ip)_conntrack plugin #175
- [memcached] support unix socket #176
- use plugin-helper for mackerel-plugin-apache2 #177
- add conntrack, jmx-jolokia, rabbitmq into package #178

Release version 0.17.0

---

mackerel-plugin-mysql/mysql.go
mackerel-plugin-mysql/mysql_test.go

fix parsing  "Buffer Pool and Memory" section when `innodb_buffer_pool_instances` is set. (Ignore "INDIVIDUAL BUFFER POOL INFO" section)

[mysql] care innodb_buffer_pool_instances

---

.travis.yml
README.md
packaging/deb/debian/changelog
packaging/deb/debian/rules
packaging/rpm/mackerel-agent-plugins.spec

- [mysql] care innodb_buffer_pool_instances #182
- Add uptime plugin #183
- [inode] use `df -iP` on linux (care line break) #185
- [mysql] support unix socket #186

Release version 0.18.0

---

mackerel-plugin-mysql/mysql.go

If `helper.Tempfile` is empty, it seems correct to set the path to the tempfile.

Fix helper.Tempfile in mysql.go

---

packaging/rpm/mackerel-agent-plugins.spec

If rpm includes dir, following conflict error occurs
```
Transaction check error:
file /usr/bin from install of mackerel-check-plugins-0.5.2-1.x86_64 conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
file /usr/bin from install of mackerel-agent-plugins-0.19.2-1.x86_64 conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
```

fix: rpm should not include dir

---

mackerel-plugin-redis/redis.go

The elasticache for redis has no `CONFIG` command!

[redis] skip to calculate capacity when CONFIG command failed

---

.travis.yml
CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec
tool/releng

- Revert "Revert "use /usr/bin/mackerel-plugin-*"" #208
- fix: redis plugin panics when redis-server is not installed. #209
- fix: rpm should not include dir #210
- [nginx] fix typo #215
- Refactoring the release process #217

Release version 0.19.3

---

mackerel-plugin-fluentd/fluentd.go
mackerel-plugin-fluentd/fluentd_test.go

Metrics fetched by `mackerel-plugin-fluentd` is updated only output plugin. So, metric other than the output plugins were so as not to send.

Do not send fluentd metrics of other than the output plugin

---

mackerel-plugin-rack-stats/README.md
mackerel-plugin-rack-stats/rack.go
mackerel-plugin-rack-stats/rack_test.go

A mackerel plugin for Rack servers.
```
$ ./mackerel-plugin-rack-stats
rack.8080.stats.queued  0.000000        1458798067
rack.8080.stats.active  0.000000        1458798067
rack.8080.stats.writing 0.000000        1458798067
rack.8080.stats.calling 0.000000        1458798067
```
```
$ ./mackerel-plugin-rack-stats -address=unix:/home/ec2-user/unicorn.sock
rack._home_ec2-user_unicorn_sock.stats.queued      0.000000        1458798089
rack._home_ec2-user_unicorn_sock.stats.active      0.000000        1458798089
rack._home_ec2-user_unicorn_sock.stats.writing     0.000000        1458798089
rack._home_ec2-user_unicorn_sock.stats.calling     0.000000        1458798089
```

Add mackerel plugin rack stats

---

mackerel-plugin-jvm/README.md

I fix README.md of mackerel-plugin-jvm, change command line option from "-jinfo" to "-jinfopath."

fix README.md of mackerel-plugin-jvm

---

mackerel-plugin-aws-ses/aws-ses.go

I tried aws-ses plugin, but can't get Bounces and Rejects metrics.
So, check mackerel-agent.log, find parse error.
```
2016/06/17 03:32:02 WARNING <metrics.plugin> Failed to parse values: strconv.ParseFloat: parsing "int": invalid synt
ax
2016/06/17 03:32:02 WARNING <metrics.plugin> Failed to parse values: strconv.ParseFloat: parsing "int": invalid synt
ax
```
environments:
mackerel-agent v0.30.4
mackerel-agent-plugins 0.20.0

Fix bug:aws-ses

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- Add PHP-FPM plugin #226
- Support password authentication of Redis #232
- Add an option to specify type and id pattern to fluentd plugin #233
- Fix bug:aws-ses #234
- fix help link #235
- xentop: get CPU %, not CPU time/min #236
- add mackerel-plugin-php-fpm into package #238

Release version 0.21.0

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- fix to use config.json to list up plugins for packaging #240
- build with go 1.6.2 #241

Release version 0.21.1

---

mackerel-plugin-fluentd/fluentd.go

I found that flag comment ( `-host` ) of mackerel-plugin-fluentd has nits typo. 🙇 
```
$ /usr/bin/mackerel-plugin-fluentd --help
Usage of /usr/bin/mackerel-plugin-fluentd:
-host string
fluentd monitor_agent port (default "localhost")
-plugin-id-pattern string
Gets the metric that matches this plugin id pattern
-plugin-type string
Gets the metric that matches this plugin type
-port string
fluentd monitor_agent port (default "24220")
-tempfile string
Temp file name
```
Thank you. 👍

Fixed flag comment of mackerel-plugin-fluentd

---

mackerel-plugin-plack/plack.go
mackerel-plugin-plack/plack_test.go

Related: https://github.com/kazeburo/Plack-Middleware-ServerStatus-Lite/pull/20
In response from Plack::Middleware::ServerStatus::Lite < 0.35, `Uptime` was a JSON string. But at its 0.35, `Uptime` became (maybe unexpectedly) a JSON number.
Because of this change, mackerel-plugin-plack became unable to parse a response from Plack::Middleware::ServerStatus::Lite 0.35.

[Plack] Adopt Plack::Middleware::ServerStatus::Lite 0.35's response

---

mackerel-plugin-apache2/apache2.go
mackerel-plugin-apache2/flags.go

Was a part of #260 
ref: https://github.com/mackerelio/go-mackerel-plugin-helper/pull/21
maybe one might want to run multiple apache instance in a host, so I implemented `PluginWithPrefix`

[apache2] Support -metric-key-prefix option and get rid of default Tempfile specification

---

mackerel-plugin-mysql/README.md
mackerel-plugin-mysql/mysql.go
mackerel-plugin-mysql/mysql_test.go

We need more metrics with MySQL plugin, so add below graphs/metrics.
I think [Percona Monitoring Plugins](https://github.com/percona/percona-monitoring-plugins) is very useful to monitoring/collecting metric for MySQL . So I refer to there code/definitions.
To enable below graphs/metrics, add command-line option `-enable_extended` . 
Default behavior is NOT change.
- MySQL Query Cache
- Qcache Queries In Cache
- Qcache Hits
- Qcache Inserts
- Qcache Not Cached
- Qcache Lowmem Prunes
- MySQL Query Cache Memory
- Query Cache Size
- Qcache Free Memory
- Qcache Total Blocks
- Qcache Free Blocks
- MySQL Sorts
- Sort Rows
- Sort Range
- Sort Merge Passes
- Sort Scan
- MySQL Temporary Objects
- Created Tmp Tables
- Created Tmp Disk Tables
- Created Tmp Files
- MySQL Files and Tables
- Table …

Add much graphs/metrics to mackerel-plugin-mysql

---

mackerel-plugin-linux/flags.go
mackerel-plugin-linux/linux.go

Currently, `mackerel-plugin-linux` fetches all supported sets of metrics, or a specified set of metrics.
With this patch, `mackerel-plugin-linux` can fetch multiple, but not all sets of metrics, by specifying `--type` option multiple times.
Example:
```
[~] # ./mackerel-plugin-linux -p swap -p diskstats -p proc_stat
linux.swap.pswpin	0.000000	1467130047
linux.swap.pswpout	0.000000	1467130047
linux.disk.elapsed.iotime_sda	3000.000000	1467130047
linux.disk.elapsed.iotime_weighted_sda	3000.000000	1467130047
linux.disk.rwtime.tsreading_sda	0.000000	1467130047
linux.disk.rwtime.tswriting_sda	3000.000000	1467130047
linux.interrupts.interrupts	6255.000000	1467130047
linux.context_switches.context_switches	15810.000000	1467130047
linux.forks.forks	180.000000	1467130047
```
Currently, …

mackerel-plugin-linux: Allow to select multiple (but not all) sets of metrics

---

mackerel-plugin-redis/redis.go

ref: #268 
- Migrated to go-mackerel-plugin-helper
- Remove default tempdir
- Since `-metric-key-prefix` is already supported, implement PluginWithPrefix interface

[redis] deal with MACKEREL_PLUGIN_WORKDIR

---

mackerel-plugin-snmp/snmp.go
mackerel-plugin-solr/solr.go
mackerel-plugin-squid/squid.go
mackerel-plugin-td-table-count/mackerel-plugin-td-table-count.go
mackerel-plugin-trafficserver/trafficserver.go
mackerel-plugin-unicorn/unicorn.go
mackerel-plugin-uptime/uptime.go
mackerel-plugin-varnish/varnish.go
mackerel-plugin-xentop/xentop.go

ref: https://github.com/mackerelio/mackerel-agent-plugins/pull/260 / https://github.com/mackerelio/go-mackerel-plugin-helper/pull/21 / https://github.com/mackerelio/go-mackerel-plugin-helper/pull/22
With https://github.com/mackerelio/go-mackerel-plugin-helper/pull/22, all we have to modify plugins to support MACKEREL_PLUGIN_WORKDIR is simple:
- [MUST] Migrate to go-mackerel-plugin-helper if it still used go-mackerel-plugin
- [MUST] Don't specify default Tempfile name (should delegated to helper)
In this p-r, I modified 9 of plugins.
- `uptime`: since this plugin already supports `-metric-key-prefix`, so (only) this plugin implemented `PluginWithPrefix`
- `td-table-count` and `snmp`:  they still used go-mackerel-plugin, so they are migrated to go-mackerel-plugin-helper
- other 6 plugins: …

Make *some* plugins to support MACKEREL_PLUGIN_WORKDIR

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- mackerel-plugin-linux: Allow to select multiple (but not all) sets of metrics #243
- Fixed flag comment of mackerel-plugin-fluentd #257
- Fix postgres.iotime.{blk_read_time,blk_write_time} #259
- [Plack] Adopt Plack::Middleware::ServerStatus::Lite 0.35's response #261
- build with Go 1.7 #262
- Add much graphs/metrics to mackerel-plugin-mysql #264
- [apache2] Support -metric-key-prefix option and get rid of default Tempfile specification #265
- [aws-rds] add `-engine` option #266
- [elasticsearch] Add open_file_descriptors metric in elasticsearch plugin #267
- Make *some* plugins to support MACKEREL_PLUGIN_WORKDIR #268
- [redis] deal with MACKEREL_PLUGIN_WORKDIR #269

Release version 0.23.0

---

mackerel-plugin-redis/redis.go
mackerel-plugin-redis/redis_test.go

The plugin can't send any valid values because [assignments to each metric](https://github.com/mackerelio/mackerel-agent-plugins/commit/ee04a0e52e161ba4a559c6129123e157b702dd4f#diff-4b78c4735dfe237f16d9d8d5c5de90a3R172) are never operated after the line started 'db'.

[redis] Fix a bug to fetch no metrics of keys and expired

---

mackerel-plugin-memcached/memcached.go
mackerel-plugin-memcached/memcached_test.go

Hi !
I think that memcached `curr_items` metric is useful for monitoring.
I added this metric to mackerel-plugin-memcached.
>| curr_items            | 64u     | Current number of items stored            |
https://github.com/memcached/memcached/blob/master/doc/protocol.txt
How about this ?
Please review, thank you 🙇 
```
$ go run memcached.go
memcached.cachesize.limit_maxbytes	67108864.000000	1477038754
memcached.cachesize.bytes	370	1477038754
memcached.items.curr_items	5.000000	1477038754
memcached.connections.curr_connections	16.000000	1477038754
memcached.hitmiss.get_hits	0.000000	1477038754
memcached.hitmiss.get_misses	0.000000	1477038754
memcached.hitmiss.delete_hits	0.000000	1477038754
memcached.hitmiss.delete_misses	0.000000	1477038754
memcached.hitmiss.incr_hits	0.000000	1477038754 …
```

Supported memcached curr_items metric

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- [redis] Fix a bug to fetch no metrics of keys and expired #272
- fix: "open file descriptors" property in elasticsearch  #273
- [memcached] Supported memcached curr_items metric #275
- [memcached] support new_items metrics #276
- [redis] s/memoty/memory/ #277

Release version 0.23.1

---

mackerel-plugin-postgres/postgres.go
mackerel-plugin-postgres/postgres_test.go

The columns `pg_stat_database.blk_read_time/blk_write_time/deadlocks/temp_bytes` are introduced at Pg 9.2. So care them.
- introduce `jmoiron/sqlx` for handling asterisk queries
- introduce `mackerelio/go-mackerel-plugin-helper`

[postgres] support Pg9.1

---

mackerel-plugin-apache2/apache2.go
mackerel-plugin-docker/docker.go
mackerel-plugin-haproxy/haproxy.go
mackerel-plugin-jvm/jvm.go
mackerel-plugin-php-apc/php-apc.go
mackerel-plugin-php-opcache/php-opcache.go

ref: https://github.com/mackerelio/mackerel-agent/pull/295
Without this change `golint` fails. example: https://travis-ci.org/mackerelio/mackerel-agent-plugins/builds/177070744

Change error strings to pass current golint

---

README.md
mackerel-plugin-twemproxy/README.md
mackerel-plugin-twemproxy/stats.go
mackerel-plugin-twemproxy/twemproxy.go
mackerel-plugin-twemproxy/twemproxy_test.go

We plan to use this plugin in production. After our test trial in production, we are sure that it's helpful for operators monitoring twemproxy(s). 
In my opinion, twemproxy is [a somewhat defacto standard](https://github.com/twitter/twemproxy#companies-using-twemproxy-in-production) proxy for redis and memcached, so I'm posting this PR.

Implement mackerel-plugin-twemproxy

---

mackerel-plugin-nvidia-smi/README.md
mackerel-plugin-nvidia-smi/nvidia_smi.go
mackerel-plugin-nvidia-smi/nvidia_smi_test.go

I'd like to add new plugin for monitoring GPUs, which utilizes [nvidia-smi](https://developer.nvidia.com/nvidia-system-management-interface)
new Metrics this plugin introduces:
- GPU Utilization
- GPU Memory Utilization
- GPU Fan Speed
- GPU Temperature
- GPU Memory Usage (free/used/total)

Add new nvidia-smi plugin

---

mackerel-plugin-aws-elb/aws-elb.go

I noticed that mackerel-plugin-aws-elb failed to get some values.
`elb.http_backend. *`, `elb.latency` failed,
`elb.healthy_host_count. *`, `elb.unhealthy_host_count.*` will succeed.
Since the difference between the two is how to set `dimensions`, 
I tried several settings of `dimensions` based on the document.
As a result, values can be acquired by excluding the following specifications.
```
{　Name: "Service", Value: "ELB", },
```

fix cloudwatch dimensions for elb

---

README.md
mackerel-plugin-aws-ec2/README.md
mackerel-plugin-aws-ec2/aws-ec2.go
mackerel-plugin-aws-ec2/aws-ec2_test.go

This plugin fetches ec2 data from Clowdwatch using [AWS SDK for Go](https://github.com/aws/aws-sdk-go).
please see [README](https://github.com/yyoshiki41/mackerel-agent-plugins/blob/aws-ec2-plugin/mackerel-plugin-aws-ec2/README.md).
``` bash
$ cd path/to/mackerel-plugin-aws-ec2
$ go run aws-ec2.go --instance-id=i-*** --region=***
ec2.DiskOps.DiskReadOps 0   1467540363
ec2.DiskOps.DiskWriteOps    0   1467540363
ec2.Network.NetworkIn   37769.800000    1467540363
ec2.Network.NetworkOut  12428.400000    1467540363
ec2.NetworkPackets.NetworkPacketsIn 51.600000   1467540363
ec2.NetworkPackets.NetworkPacketsOut    41  1467540363
ec2.StatusCheckFailed.StatusCheckFailed 0   1467540363
ec2.StatusCheckFailed.StatusCheckFailed_Instance    0   1467540363
ec2.StatusCheckFailed.StatusCheckFailed_System …
```

Implement mackerel-plugin-aws-ec2

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- Implement mackerel-plugin-aws-ec2 #248
- [postgres] support Pg9.1 #274
- Add new nvidia-smi plugin #280
- [jvm] Add notice about user to README #281
- Implement mackerel-plugin-twemproxy #283
- fix cloudwatch dimensions for elb #284
- Change error strings to pass current golint #285
- Add mackerel-plugin-twemproxy to package #286

Release version 0.24.0

---

mackerel-plugin-apache2/lib/apache2.go
mackerel-plugin-apache2/lib/apache2_test.go

According to [spec of `/api/v0/graph-defs/create`](https://mackerel.io/api-docs/entry/host-metrics#post-graphdef), metric name ending with dot (`.`) is invalid.
A metric name will be changed.
```
custom.apache2.scoreboard.score-. => custom.apache2.scoreboard.score-
```

[apache2] Change metric name not to end with dot

---

mackerel-plugin-murmur/lib/murmur.go

Its import path changed. ref: https://github.com/layeh/gumble/commit/1f539c85da553378dacd9814ce9b23142e4dcaf3
Otherwise we cannot `make testdeps` ref: https://travis-ci.org/mackerelio/mackerel-agent-plugins/builds/186792387
```
[github.com/mackerelio/mackerel-agent-plugins]$ make testdeps
go get -d -v -t ./...
Fetching https://layeh.com/gumble/gumble/MumbleProto?go-get=1
Parsing meta tags from https://layeh.com/gumble/gumble/MumbleProto?go-get=1 (status code 200)
get "layeh.com/gumble/gumble/MumbleProto": found meta tag main.metaImport{Prefix:"layeh.com/gumble", VCS:"git", RepoRoot:"https://github.com/layeh/gumble"} at https://layeh.com/gumble/gumble/MumbleProto?go-get=1
get "layeh.com/gumble/gumble/MumbleProto": verifying non-authoritative meta tag
Fetching …
```

[nit] change import path for github.com/layeh/gumble/gumble

---

mackerel-plugin-aws-cloudfront/lib/aws-cloudfront.go
mackerel-plugin-aws-ec2-cpucredit/lib/aws-ec2-cpucredit.go
mackerel-plugin-aws-elasticache/lib/aws-elasticache.go
mackerel-plugin-aws-elasticsearch/lib/aws-elasticsearch.go
mackerel-plugin-aws-elb/lib/aws-elb.go
mackerel-plugin-aws-rds/lib/aws-rds.go

- https://github.com/crowdmob/goamz is deprecated
- (And https://github.com/AdRoll/goamz is suggested)
- Currently we cannot build plugins using  crowdmob/goamz
- Maybe official SDK https://github.com/aws/aws-sdk-go is enough
- For aws-{cloudfront, ec2-cpuredit, elasticache, elasticsearch, elb, rds}, Migrate from goamz to aws-sdk-go
- aws-ses also uses goamz, but it only uses its authentication part and we can build it now, so keep it
- And practically it uses go-ses, which uses goamz's authentication interface, therefore it's harder to migrate to aws-sdk-go
- And I removed explicitly default Tempfile definition from some plugins
- These changes improve compatibility with `MACKEREL_PLUGIN_WORKDIR` env.

migrate from goamz to aws-sdk-go

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- Change directory structure convention of each plugin #289
- [apache2] fix typo in graphdef #291
- [apache2] Change metric name not to end with dot #293
- add mackerel-plugin-windows-server-sessions #294
- migrate from goamz to aws-sdk-go #295
- [docker] Add timeout for API request #296
- fix directory structure #298
- [ci skip]Update readme #299

Release version 0.25.0

---

mackerel-plugin-jvm/lib/jvm.go

Due to the references, the unit of gc times are available in seconds. However, the jvm plugin
- outputs the label as msec.
- scales incorrectly to calculate the gc time rate to 60 seconds.
I fixed
- the label of the graph of GC time (msec -> sec).
- the scale of GC time percentage.
References
http://docs.oracle.com/javase/7/docs/technotes/tools/share/jstat.html#gcutil_option
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstat.html

Fix the label and scale in jvm plugin

---

mackerel-plugin-aws-cloudfront/lib/aws-cloudfront.go

Initial value of `latest` should be latest timestamp (like `now`).  I mistakingly change it on https://github.com/mackerelio/mackerel-agent-plugins/commit/e96e51e3e4e778b8332da346e62786c47d4af805#diff-9c38f5b9ec8b7f4bc9b48e08f544be3cR114 .

[aws-cloudfront] Fix regression #295

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- [aws-rds] fix metric name #306
- [aws-ses] ses.stats is unit type #308
- [aws-cloudfront] Fix regression #295 #309

Release version 0.25.2

---

mackerel-plugin-aws-rds/lib/metrics.go

* CPUUtilization
* CPUCreditBalance //only t2 instance
* CPUCreditUsage //only t2 instance
* DatabaseConnections
* FreeableMemory
```shell
rds.CacheHitRatio.ResultSetCacheHitRatio	17.307692	1485506194
rds.CacheHitRatio.BufferCacheHitRatio	100	1485506194
rds.AuroraReplicaLag.AuroraReplicaLagMaximum	26.157000	1485506194
rds.AuroraReplicaLag.AuroraReplicaLagMinimum	26.157000	1485506194
rds.Deadlocks.Deadlocks	0	1485506194
rds.Transaction.ActiveTransactions	0	1485506194
rds.Transaction.BlockedTransactions	0	1485506194
rds.Throughput.SelectThroughput	4.333406	1485506194
rds.Throughput.InsertThroughput	0.533342	1485506194
rds.Throughput.UpdateThroughput	0.250004	1485506194
rds.Throughput.DeleteThroughput	0	1485506194
rds.Throughput.CommitThroughput	0.750013	1485506194 …
```

[aws-rds] Make it possible to get metrics from Aurora.

---

CHANGELOG.md
packaging/deb/debian/changelog
packaging/rpm/mackerel-agent-plugins.spec

- Feature/gcp compute engine #304
- [aws-rds] Make it possible to get metrics from Aurora. #307
- [multicore]fix tempfile path #311

Release version 0.25.3

---

.travis.yml
Makefile
circle.yml

Since mackerel-agent-plugins' build process is simple (compared to mackerel-agent), maybe native `go build` is enough.

Cross compile by go's native cross build, not by gox

---

mackerel-plugin-twemproxy/lib/twemproxy.go
mackerel-plugin-twemproxy/lib/twemproxy_test.go

* In twemproxy v0.3 excluded because total_connections and curr_connections does not exist.
* Added total_server_error. (Assuming monitoring of multiple pool collectively)

Support twemproxy v0.3, Add total_server_error

---

mackerel-plugin-uwsgi-vassal/README.md
mackerel-plugin-uwsgi-vassal/lib/uwsgi_vassal.go
mackerel-plugin-uwsgi-vassal/main.go

This plugin supports uWSGI worker metrics.  These metrics need to be provided by uWSGI `--stats` option in vassal not emperor (`--emperor-stats`).

Add uWSGI vassal plugin

---

mackerel-plugin-php-fpm/lib/php-fpm.go

ref: #250, #255, etc...
Since mackerel-plugin-php-fpm already supports `-metric-key-prefix` option, it's natural to implement PluginWithPrefix interface.

[php-fpm] Implement PluginWithPrefix interfarce

---

mackerel-plugin-aws-ec2/lib/aws-ec2.go
mackerel-plugin-aws-elasticache/lib/aws-elasticache.go
mackerel-plugin-docker/lib/docker.go
mackerel-plugin-elasticsearch/lib/elasticsearch.go
mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-gcp-compute-engine/lib/gcp-compute-engine.go
mackerel-plugin-gearmand/lib/gearmand.go
mackerel-plugin-jmx-jolokia/lib/jmx-jolokia.go
mackerel-plugin-jvm/lib/jvm.go
mackerel-plugin-mongodb/lib/mongodb.go
mackerel-plugin-munin/lib/munin.go
mackerel-plugin-murmur/lib/murmur.go

ref: #268, #269, #301
With this p-r and #338, all plugins use `MACKEREL_PLUGIN_WORKDIR` for Tempfile by default.

Use SetTempfileByBasename to support MACKEREL_PLUGIN_WORKDIR

---

mackerel-plugin-nginx/README.md

Hi !
I found that `mackerel-plugin-nginx` already supports `-header` option via https://github.com/mackerelio/mackerel-agent-plugins/pull/78 .
We can use `-header` option like `-header='User-Agent: xxx'` .
```sh
$ /usr/bin/mackerel-plugin-nginx -h
Usage of /usr/bin/mackerel-plugin-nginx:
-header value
Set http header (e.g. "Host: servername")
-host string
Hostname (default "localhost")
-path string
Path (default "/nginx_status")
-port string
Port (default "8080")
-scheme string
Scheme (default "http")
-tempfile string
Temp file name
-uri string
URI
```
So, I fixed `mackerel-plugin-nginx/README.md` .
- Added `-header` option
- Added `-uri` option
- Switched order of the options according to output `-h`
Thanks 👍

Fixed mackerel-plugin-nginx/README.md

---

mackerel-plugin-aws-rds/lib/metrics.go

[aws-rds] Fix "Latency" metric label

---

mackerel-plugin-redash/README.md
mackerel-plugin-redash/lib/redash.go
mackerel-plugin-redash/lib/redash_test.go
mackerel-plugin-redash/lib/unsafe_stats.go
mackerel-plugin-redash/main.go

We plan to use this plugin in production. After our test trial in production, we are sure that it's helpful for operators monitoring redash. 
Usage example of each graph is as follows.
- Queue count (wait)
- Used to detect if queue is stuck
- Scheduled count
- Ease of grasping usage situation and trend. It leads to judgment of which worker to increase
- State count (failed)
- Used to detect failure of query

Implemented mackerel-plugin-redash

---

mackerel-plugin-postgres/lib/postgres.go

`pg_dataase_size` throws error when cannot connect the database.
https://github.com/postgres/postgres/blob/REL9_6_3/src/backend/utils/adt/dbsize.c#L92-L96

postgres: collect dbsize only if connectable

---

mackerel-plugin-elasticsearch/lib/elasticsearch.go
mackerel-plugin-inode/lib/inode.go
mackerel-plugin-jmx-jolokia/lib/jmx-jolokia.go
mackerel-plugin-jvm/lib/jvm.go
mackerel-plugin-mongodb/lib/mongodb.go
mackerel-plugin-postgres/lib/postgres.go
mackerel-plugin-proc-fd/lib/proc_fd.go
mackerel-plugin-redis/lib/redis.go
mackerel-plugin-solr/lib/solr.go
mackerel-plugin-td-table-count/lib/mackerel-plugin-td-table-count.go
mackerel-plugin-unicorn/lib/unicorn.go
mackerel-plugin-windows-server-sessions/lib/sessions.go

ref: https://github.com/mackerelio/mackerel-agent/pull/395
Since (currently) their implementations are the same, just replacing `import` is enough.

Use mackerelio/golib/logging as logger, not mackerelio/mackerel-agent/logging

---

mackerel-plugin-aws-elasticsearch/lib/aws-elasticsearch.go

This PR fixes following error:
```
$ make lint
go get -d -v -t ./...
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/cover
go get github.com/pierrre/gotestcover
go get github.com/mattn/goveralls
go vet ./...
mackerel-plugin-aws-elasticsearch/lib/aws-elasticsearch.go:238: arg met.MetricName for printf verb %s of wrong type: *string
exit status 1
make: *** [lint] Error 1
```

Fix lint error on aws-elasticsearch

---

mackerel-plugin-aws-dynamodb/lib/aws-dynamo-db.go

Recently added to CloudWatch, and I missed to incude this metrics.

[aws-dynamodb] add TimeToLiveDeletedItemCount metrics

---

mackerel-plugin-solr/lib/solr.go

According to [Performance Statistics Reference](https://cwiki.apache.org/confluence/display/solr/Performance+Statistics+Reference), `requests` attribute is cumulative value.
> Total number of requests made since the Solr process was started.
We might as well view it as differential value on a graph.

Fix a graph definition for Apache Solr's cumulative metric

---

mackerel-plugin-linux/lib/linux_test.go

`getProc` just executes `cat` and returns its content, so imo we don't have to test its contents.
(This test causes failure on https://travis-ci.org/mackerelio/mackerel-agent-plugins/builds/266481092,  in which environment `/proc/diskstats` does not contain `"ram0"`.)

[nit] [mackerel-plugin-linux] Remove a test which is not necessary and may fall sometimes

---

mackerel-plugin-plack/lib/plack.go
mackerel-plugin-plack/lib/plack_test.go

Main purpose is to use mackerel-plugin-plack to monitor other platforms which is only PARTIALLY compatible with Plack::Middleware::ServerStatus::Lite, but I believe this is harmless for original Plack::Middleware::ServerStatus::Lite.

[plack] Don't raise errors when parsing JSON fields failed

---

mackerel-plugin-aws-dynamodb/lib/aws-dynamo-db.go

mackerel-plugin-aws-dynamodb does 7 + 5 * n (n = available operational dimensions)  requests on execute, and currently they're requested in series. I'd like to introduce `golang.org/x/sync/errgroup` to request them in parallel.

[aws-dynamodb] Refactor and parallelize CloudWatch request with errgroup

---

mackerel-plugin-redis/lib/redis.go

TravisCI build is failed with "mackerel-plugin-redis/lib/redis.go:93:2: redundant if ...; err != nil check, just return error instead" ( https://travis-ci.org/mackerelio/mackerel-agent-plugins/jobs/277135454#L1091 ).
This is because golint's specification change (https://github.com/golang/lint/pull/319).
So I fixed redis.go to pass golint.

Fix redundant error by golint in redis.go

---

mackerel-plugin-accesslog/lib/accesslog.go
mackerel-plugin-accesslog/lib/accesslog_test.go

This patch makes be able to specify access log format by plugin option.
It's good when axslogparser failed to detect log format.

[accesslog] Feature/accesslog/customize parser

---

mackerel-plugin-aws-dynamodb/lib/aws-dynamo-db.go

- ReadThrottleEvents metrics are missing, so added
- For ReadThrotttleEvents and WriteThrottleEvents metrics, fill 0 when values are not present

Update mackerel-plugin-dynamodb plugin

---

mackerel-plugin-twemproxy/lib/twemproxy.go
mackerel-plugin-twemproxy/lib/twemproxy_test.go

When collecting metrics for each pool of twemproxy, it is needed to explicitly specify `-enable-each-pool-metrics` option now.
This is an incompatible change, but I think that sending the metrics of each pool by default is noisy and it may even cause a metric increase that the user doesn't expect.

[twemproxy] [incompatible] add `-enable-each-pool-metrics` option

---

mackerel-plugin-twemproxy/lib/twemproxy.go
mackerel-plugin-twemproxy/lib/twemproxy_test.go

At #419, I reduced the number of standard metrics of twemproxy plugin, but is was too much reduction.
I changed that the metric for each pool is collected by default, and it is possible to switch whether or not to collect detailed metric for each server as option.

Add `-enable-each-server-metrics` option and remove `-enable-each-pool-metrics`

---

mackerel-plugin-aws-elasticsearch/lib/aws-elasticsearch.go

I improved CloudWatch Statistic type by referring to AWS Management Console.
And I added some metrics.

[aws-elasticsearch] Improve CloudWatch Statistic type and add some metrics

---

mackerel-plugin-uptime/lib/uptime.go

Recently go-mackerel-plugin is recommended more then go-mackerel-plugin-helper.

[uptime] use go-mackerel-plugin instead of using go-mackerel-plugin-helper

---

mackerel-plugin-aws-cloudfront/README.md
mackerel-plugin-aws-cloudfront/lib/aws-cloudfront.go

Added `-metric-key-prefix` option to support multiple cloudfront distributions.

[cloudfront] add -metric-key-prefix option

---

mackerel-plugin-gostats/lib/mackerel-plugin-gostats.go
mackerel-plugin-gostats/lib/mackerel-plugin-gostats_test.go

We recommend go-mackerel-plugin over go-mackerel-plugin-helper.

[gostats] Use go-mackerel-plugin instead of go-mackerel-plugin-helper

---

mackerel-plugin-postgres/lib/postgres.go
mackerel-plugin-postgres/lib/postgres_test.go

- Support parsing version of Azure Database for PostgreSQL and PostgreSQL 10
- Change pg_stat_activity query to exclude stats which has null state value
This is a response for `pg_stat_activity` on my local PostgreSQL 10 running in Docker:
```
postgres=# select * from pg_stat_activity;
datid | datname  | pid | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type |     wait_event      | state  | backend_xid | backend_xmin |              query              |    backend_type
-------+----------+-----+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+- …
```

Improve mackerel-plugin-postgres

---

mackerel-plugin-docker/lib/docker.go

Legacy docker command reports server api version as `Server API version: x.yy` form:
```
$ sudo docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```
But recently it does not report in the form:
```
$ docker version
Client:
Version:      17.09.0-ce
API version:  1.32
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:40:09 2017
OS/Arch:      darwin/amd64
Server:
Version:      17.09.0-ce
API version:  1.32 (minimum version 1.12)
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:45:38 2017
OS/Arch:      linux/amd64 …
```

[docker] Don't log when regexp does not match

---

mackerel-plugin-aws-ec2-ebs/lib/aws-ec2-ebs.go

Some metrics does not have datapoints when the volume is idle, therefore do not output such error to Stderr, to keep clean mackerel-agent.log
BEFORE:
```
$ mackerel-plugin-aws-ec2-ebs
2017/11/16 21:26:13 vol-DUMMY fetched no datapoints:VolumeReadBytes
2017/11/16 21:26:13 vol-DUMMY fetched no datapoints:VolumeReadBytes
2017/11/16 21:26:13 vol-DUMMY fetched no datapoints:VolumeTotalReadTime
ec2.ebs.queue_length.vol-DUMMY.queue_length	0.000100	1510835172
ec2.ebs.idle_time.vol-DUMMY.idle_time	99.990000	1510835172
ec2.ebs.bandwidth.vol-DUMMY.write	3973.120000	1510835172
ec2.ebs.latency.vol-DUMMY.write	0.215827	1510835172
ec2.ebs.burst_balance.vol-DUMMY.burst_balance	100.000000	1510835172
ec2.ebs.throughput.vol-DUMMY.read	0.000000	1510835172
ec2.ebs.throughput.vol-DUMMY.write	0.463333 …
```

[aws-ec2-ebs] Do not log "fetched no datapoints" error

---

mackerel-plugin-docker/lib/docker.go

mackerel-plugin-docker sometimes panics with `fatal error: concurrent map writes`, since it does not take a lock on manipulating `map` in goroutine.

[docker] Avoid concurrent map writes by multiple goroutines

---

mackerel-plugin-linux/lib/linux.go
mackerel-plugin-linux/lib/linux_test.go

- Use `file.Open("hoge")` instead of `exec.command("cat", "hoge")`
- Use `io.Reader` as interface between reading and parsing
- `collectWho()` is so simple therefore it still uses String as interface
- Rename `{collect,parse}Ss()` to `{collect,parse}NetworkStat()`
- I'd like to add `netstat` implementation to this stat in future, so renamed

[nit] refactor mackerel-plugin-linux

---

mackerel-plugin-jvm/README.md
mackerel-plugin-jvm/lib/jvm.go
mackerel-plugin-jvm/lib/jvm_test.go

mackerel-plugin-jvm has `-host` and `-port` option but they don't work as expected.
I'd like change those options to `-remote` option and make it work with rmi protocol.
In target host
```
/tmp$ cat jstatd.policy
grant codebase "file:${java.home}/../lib/tools.jar" {
permission java.security.AllPermission;
};
/tmp$ jstatd -J-Djava.security.policy=/tmp/jstatd.policy -p [Port] -J-Djava.rmi.server.hostname=[Hostname]
```
In monitoring host:
```
$ ./mackerel-plugin-jvm -javaname XXX -remote [targetHostName:targetPort]
```

Jvm remote

---

mackerel-plugin-docker/lib/docker.go

Changed graph unit and scaled `blkio.io_serviced` to get IOPS properly.

Improve docker plugin

---

tool/create-release-pullrequest

ref: #450 , etc.
With current master branch, `make release` attempts to add links to all plugins' README even if they've been moved to other repositories.
This patch adds simple filtering by checking existence of `mackerel-plugin-XXX/lib`.

Don't add plugins README which has been moved

---

mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-gcp-compute-engine/lib/gcp-compute-engine.go
mackerel-plugin-json/lib/json.go
mackerel-plugin-php-fpm/lib/php-fpm.go

The client must close the response body.
See Package http Overview: https://golang.org/pkg/net/http/

add that close the response body

---

mackerel-plugin-redis/README.md
mackerel-plugin-redis/lib/redis.go
mackerel-plugin-redis/lib/redis_test.go

This patch is useful when CONFIG command has renamed or disabled for failsafe or security reasons.
If `-config-command=""` is specified, the metric acquisition with the CONFIG command is skipped.

Redis Plugin supports custom CONFIG command

---

mackerel-plugin-mysql/lib/mysql.go

Since the Aurora reader node does not support `SHOW ENGINE INNODB STATUS`, so skip fetchShowInnodbStatus in mackerel-agent-plugin-mysql.
~Also, skip calculation of PercentageOfBufferPool as pool_size is be 0 when skipped fetchShowInnodbStatus.~
Don't skip calc PercentageOfBufferPool.
Several values can be used from `SHOW VARIABLES`, so use pseudoFetchShowInnodbStatus instead of fetchShowInnodbStatus when target node is Aurora reader.

MySQL Plugin support Aurora reader node

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

ref: #462 
During review of #462, I realized some stats parsed from `show engine innodb status` can be taken from `show status` actually.  Since parsing InnoDB status are complicated and difficult, imo it's better to obtain those stats from `show status`.
And also, some stats are parsed but not used, so I removed them, (`rows_{deleted,inserted,read,updated}`).

[mysql] Fix some InnoDB stats

---

mackerel-plugin-mysql/lib/mysql.go

Those stats has been obtained as current value from `show engine innodb status`.
With #469, mackerel-plugin-mysql obtains those stats from `show status`, but those in `show status` are counter value and needs to be set `Diff: true`, and to be scaled `*(1/60)`.

[mysql] set Diff: true for some stats which are actually counter values

---

mackerel-plugin-mysql/lib/mysql.go

delivered from #470.
Message will be following:
```
$ ./mackerel-plugin-mysql -username nagios -password nagios
2017/12/20 19:16:35 FetchMetrics (InnoDB Status):  Received #1286 error from MySQL server: "Unknown table engine 'INNODB'"
2017/12/20 19:16:35 Hint: If you don't use InnoDB and see InnoDB Status error, you should set -disable_innodb
```

[mysql] add a hint for -disable_innodb

---

mackerel-plugin-postgres/lib/postgres.go

tested with PostgreSQL 9.3.14(Amazon RDS)

[postgres]state may be null even in old versions

---

Makefile

Fix #484
In gnumake rules, `*.go` will resolved to proper files when ANY file exists, but will be resolved to a (non-exists) file `*.go` itself when NO files found.
To avoid this, 
- add main.go to dependency
- use `wildcard` function to avoid `*.go`
- ref: https://www.gnu.org/software/make/manual/html_node/Wildcard-Function.html#Wildcard-Function
- add `.SECONDEXPANSION` to resolve `wildcard` after `%` resolved
- ref: https://www.gnu.org/software/make/manual/html_node/Secondary-Expansion.html

make `make build` works for some plugins which moved out from this repository

---

Makefile

[[ ISSUE ]]
1. On BSD(NetBSD, FreeBSD, OpenBSD), 'make' is 'BSD make'.
so 'make build' will use 'BSD make', on BSD.
2. 'BSD make' is not support 'The shell Function'
see. https://www.gnu.org/software/make/manual/make.html#Shell-Function
in Makefile:
GOOS   ?= $(shell go env GOOS)
GOARCH ?= $(shell go env GOARCH)
this is not support BSD make.
==> BSD need to use 'gmake'.
'gmake' is 'GNU make'. 'gmake' is provided package, on BSD.
3. 'make' written directry (so used 'BSD make' on BSD)
in Makefile:
make $(BINDIR)/$$i;
etc..
4. 'BSD make' is not support 'Pattern rules'
see. Features of GNU make
https://www.gnu.org/software/make/manual/html_node/Features.html
in Makefile:
$(BINDIR)/mackerel-plugin-%: mackerel-plugin-%/main.go $$(wildcard mackerel-plugin-%/lib/*.go)
'BSD make' is not support …

Support BSD

---

mackerel-plugin-redis/lib/redis.go

This is a small fix that I found while looking through the diff of #488, there's a typo in a variable name.

[nit] fix a variable name typo

---

mackerel-plugin-mongodb/lib/mongodb.go
mackerel-plugin-mongodb/lib/mongodb_docker_test.go
mackerel-plugin-mongodb/lib/mongodb_test.go

- [go\-mgo/mgo](https://github.com/go-mgo/mgo) is unmainted
- https://twitter.com/gniemeyer/status/951846808061448192
- migrate to [globalsign/mgo](https://github.com/globalsign/mgo)

Migrate from `go-mgo/mgo` to `globalsign/mgo`

---

mackerel-plugin-aws-s3-requests/README.md
mackerel-plugin-aws-s3-requests/lib/aws-s3-requests.go
mackerel-plugin-aws-s3-requests/main.go
mackerel-plugin_gen.go
packaging/config.json

AWS S3 Requests metrics plugin.
Initial implementation is available at https://github.com/astj/mackerel-plugin-aws-s3-requests.

Add mackerel-plugin-aws-s3-requests

---

.travis.yml

This pull request upgrades the version of Go on TravisCI. 1.9.x is resolved by https://github.com/travis-ci/travis-build.

[nit] Upgrade Go version to 1.9.x

---

mackerel-plugin-postgres/lib/postgres.go

This PR adds amount of transaction location change metric as `xlog_location.xlog_location_bytes` in postgresql plugin. When postgres is in recovery, this metric is offered with `0`.

[postgres] Add amount of xlog_location change

---

mackerel-plugin-aws-ec2-cpucredit/lib/aws-ec2-cpucredit.go

Ref: https://aws.amazon.com/jp/blogs/aws/new-t2-unlimited-going-beyond-the-burst-with-high-performance/
Example output using surplus balance:
```
$ ./mackerel-plugin-aws-ec2-cpucredit
ec2.cpucredit.usage	5.849346	1522223184
ec2.cpucredit.balance	0	1522223184
ec2.cpucredit.surplus_balance	2.166543	1522223184
ec2.cpucredit.surplus_charged	0	1522223184
```

[aws-ec2-cpucredit] Add T2 unlimited CPU credit metrics

---

mackerel-plugin-linux/lib/linux.go
mackerel-plugin-linux/lib/linux_test.go

Fix for collectiong ioDrive(FusionIO) diskstats.
- ioDrive device name is "fioa", "fiob", ...
```
$ ls -l /sys/block/
total 0
...
lrwxrwxrwx 1 root root 0 Sep 29  2017 fioa -> ../devices/virtual/block/fioa
...
```

fix for collectiong ioDrive(FusionIO) diskstats

---

mackerel-plugin-aws-rds/lib/aws-rds.go

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Monitoring.html
> BurstBalance
> The percent of General Purpose SSD (gp2) burst-bucket I/O credits available.
> Units: Percent

[aws-rds]add BurstBalance metric

---

mackerel-plugin-aws-rds/lib/aws-rds.go
mackerel-plugin-aws-rds/lib/metrics.go

DiskQueueDepth: fixed typo
> DiskQueueDepth
> The number of outstanding IOs (read/write requests) waiting to access the disk.
> Units: Count
*Throughput(aurora): fixed unit
> SelectThroughput: The average number of select queries per second.
> InsertThroughput: The average number of insert queries per second.
> UpdateThroughput: The average number of update queries per second.
> DeleteThroughput: The average number of delete queries per second.
> CommitThroughput: The average number of commit operations per second.
> DDLThroughput: The average number of DDL requests per second.
> DMLThroughput: The average number of inserts, updates, and deletes per second.
cf https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rds-metricscollected.html

[aws-rds]fix unit for some metrics

---

mackerel-plugin-aws-s3-requests/lib/aws-s3-requests.go

Adjust s3 CloudWatch GetMetricStaticsInput.
- CloudWatch metrics sometimes delays more than 3 minutes, therefore increase the duration
- S3 requests statistics are available with 1 min resolution, so set period to 60

[aws-s3-requests] CloudWatch GetMetricStatics parameters

---

mackerel-plugin-aws-kinesis-streams/lib/aws-kinesis-streams.go

We have mistaken metric names of aws kinesis stream, so we failed to collect following metrics
- ReadProvisionedThroughputExceeded
- WriteProvisionedThroughputExceeded
This pull request fixes these names.

[aws-kinesis-streams] Collect (Write|Read)ProvisionedThroughputExceeded metrics correctly

---

mackerel-plugin-mssql/README.md
mackerel-plugin-mssql/lib/mssql_other.go
mackerel-plugin-mssql/lib/mssql_test.go
mackerel-plugin-mssql/lib/mssql_windows.go
mackerel-plugin-mssql/lib/wmi.go
mackerel-plugin-mssql/main.go

This add MSSQL plugin that support SQL Server and SQL Express both. Below is usage of this plugin.
```
mackerel-plugin-mssql [-instance=<SQLSERVER|SQLEXPRESS>] [-tempfile=<tempfile>]
```

add MSSQL plugin

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

This pull request fixes the metric values of `custom.mysql.innodb_transactions.innodb_transactions`. We mistakenly decode transaction id in decimal numbers assuming hex format.
Transaction ids are printed in hex format in version < 5.6.4, but it is now printed in decimal. 
Ref: https://github.com/mysql/mysql-server/commit/3420dc52b68c9afcee0a19ba7c19a73c2fbb2913

[mysql] Fix decoding transaction ids from mysql innodb status

---

mackerel-plugin-mysql/lib/mysql.go

This is just a preference, but strings.HasPrefix should be better than strings.Index(...) == 0.

[nit] [mysql] prefer strings.HasPrefix / strings.Contains rather than strings.Index

---

mackerel-plugin-postgres/lib/postgres.go

Because pg_current_xlog_location() is currently not supported for Amazon Aurora

[postgres]Ignore error to support Aurora

---

mackerel-plugin-apache2/lib/apache2.go
mackerel-plugin-elasticsearch/lib/elasticsearch.go
mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-flume/lib/flume.go
mackerel-plugin-gostats/lib/mackerel-plugin-gostats.go
mackerel-plugin-graphite/lib/graphite.go
mackerel-plugin-h2o/lib/h2o.go
mackerel-plugin-haproxy/lib/haproxy.go
mackerel-plugin-jmx-jolokia/lib/jmx-jolokia.go
mackerel-plugin-nginx/lib/nginx.go
mackerel-plugin-php-apc/lib/php-apc.go
mackerel-plugin-php-fpm/lib/php-fpm.go
mackerel-plugin-php-opcache/lib/php-opcache.go
mackerel-plugin-plack/lib/plack.go
mackerel-plugin-rack-stats/lib/rack.go
mackerel-plugin-redash/lib/unsafe_stats.go
mackerel-plugin-solr/lib/solr.go
mackerel-plugin-uwsgi-vassal/lib/uwsgi_vassal.go

Previously they're all `Go-http-client/x.y`.
(Probably we should announce this change)

Set (default) User-Agent header to HTTP requests

---

mackerel-plugin-redash/README.md
mackerel-plugin-redash/lib/redash.go

Add `-api-key` option.
Synopsis:
```
mackerel-plugin-redash [-metric-key-prefix=redash] [-timeout=5] \
[-uri=http://localhost/api/admin/queries/tasks?api_key=hoge] \
[-api-key=YOUR_REDASH_API_KEY]
```
The value of `-api_key` is used as uri's one if the option is presented or `REDASH_API_KEY` environment variable is set. 
Specially, an admin's API key of Redash is strong. I want to remove it in config file to prevent reading it from other users who are in the host.

Add redash api-key option

---

mackerel-plugin-redash/lib/redash.go

ref: #535 
As I wrote in comment, we(I) recommend using -api-key option, but it's still possible specify ?api_key=XXX directly in -uri option, for compatibility.

[nit] [redash] still accept including ?api_key in -uri, for compatibility

---

mackerel-plugin-redis/lib/redis.go

Sorry, in previous PR #537, I misunderstood `Diff` parameter meaning.
`evicted_keys` should set `Diff` to true because it is counter number.

[redis] Change evicted_keys.Diff to true

---

mackerel-plugin-linux/lib/linux.go
mackerel-plugin-linux/lib/linux_test.go

The width of ss's Netid column may be a minimum of 5.
https://github.com/sivasankariit/iproute2/blob/1179ab033c31d2c67f406be5bcd5e4c0685855fe/misc/ss.c#L3111-L3117

[linux] consider the case where the width of the Netid column is only 5 in the output of ss

---

mackerel-plugin-php-fpm/README.md

[php-fpm][nit] fix typo

---

mackerel-plugin-twemproxy/lib/twemproxy_test.go

https://github.com/lestrrat/go-tcputil is deprecated in favor of https://github.com/lestrrat-go/tcputil

[nit] Fix moved repository: lestrrat-go/tcptest

---

mackerel-plugin-haproxy/README.md

fix #498 
The current sample configuration in README.md is old style and does not work in the newer version (1.6 or later), with raising errors as following. So I fixed it.
```
[ALERT] 071/105745 (54631) : parsing [/usr/local/etc/haproxy.cfg:1] : 'listen' cannot handle unexpected argument '*:8088'.
[ALERT] 071/105745 (54631) : parsing [/usr/local/etc/haproxy.cfg:1] : please use the 'bind' keyword for listening addresses.
[ALERT] 071/105745 (54631) : Error(s) found in configuration file : /usr/local/etc/haproxy.cfg
[ALERT] 071/105745 (54631) : Fatal errors found in configuration.
```

[haproxy] fix example of haproxy.cfg in README.md

---

mackerel-plugin-accesslog/lib/accesslog.go

In the first scan, the count metrics are omitted because they become noises currently.
In this pull request I omit percentile metrics for the same reason, and now any metrics are not returned on the first scan.

[accesslog] don't return any metrics on the first scan

---

mackerel-plugin-mysql/README.md
mackerel-plugin-mysql/lib/mysql.go

I added `-debug` option.
This option allows that prints debugging logs to stderr. For example, below logs is results of when `-debug` is enabled.
```
2019/05/08 11:48:23 [ 0 ->] Init packet:
2019/05/08 11:48:23         ProtVer=10, ServVer="8.0.16" Status=0x2
2019/05/08 11:48:23 [ 1 <-] Authentication packet
2019/05/08 11:48:23 [ 3 ->] OK packet:
2019/05/08 11:48:23         AffectedRows=0 InsertId=0x0 Status=0x2 WarningCount=0 Message=""
2019/05/08 11:48:23 [ 0 <-] Command packet: Cmd=0x3 show /*!50002 global */ status
2019/05/08 11:48:23 [ 1 ->] Result set header packet:
2019/05/08 11:48:23         FieldCount=2
2019/05/08 11:48:23 [ 2 ->] Field packet:
2019/05/08 11:48:23         Name="Variable_name" Type=0xfd
2019/05/08 11:48:23 [ 3 ->] Field packet:
2019/05/08 11:48:23 …
```

[mysql] add -debug option for troubleshooting

---

mackerel-plugin-jvm/lib/jvm.go

This p-r introduces a breaking change of default behavior, but I believe in most cases the change does not matter.
When jstat and other commands are placed somewhere else (like `/opt/java/bin/jstat`), currently we have to specify executable paths 3 times:
```
mackerel-plugin-jvm -jstatpath=/opt/java/bin/jstat -jpspath=/opt/java/bin/jps -jinfopath=/opt/java/bin/jinfo
```
Considering following two cases, I'd like to change default path of jstat and its friends from `/usr/bin/jXXX` to `${JAVA_HOME}/bin/jXXX`. when `JAVA_HOME` is not empty.
considerations:
- in many cases users set preferred `JAVA_HOME` 
- users can override `JAVA_HOME` by  `env` option of mackerel-agent.conf

[plugin-jvm] prefer ${JAVA_HOME}/bin/j** if JAVA_HOME is set

---

mackerel-plugin-solr/README.md
mackerel-plugin-solr/lib/solr.go
mackerel-plugin-solr/lib/solr_test.go
mackerel-plugin-solr/lib/stats/5.5.4/system.json
mackerel-plugin-solr/lib/stats/6.4.2/system.json
mackerel-plugin-solr/lib/stats/7.7.2/cache.json
mackerel-plugin-solr/lib/stats/7.7.2/cores.json
mackerel-plugin-solr/lib/stats/7.7.2/query.json
mackerel-plugin-solr/lib/stats/7.7.2/replication.json
mackerel-plugin-solr/lib/stats/7.7.2/system.json
mackerel-plugin-solr/lib/stats/7.7.2/update.json
mackerel-plugin-solr/lib/stats/8.1.1/cache.json
mackerel-plugin-solr/lib/stats/8.1.1/cores.json
mackerel-plugin-solr/lib/stats/8.1.1/query.json
mackerel-plugin-solr/lib/stats/8.1.1/replication.json
mackerel-plugin-solr/lib/stats/8.1.1/system.json
mackerel-plugin-solr/lib/stats/8.1.1/update.json

Hi,
We'd like to migrate Apache Solr from `5.x` to `8.x`, however, it seems several metrics keys are changed and removed since `7.x` like follows.
| Label | `5.x` | `6.x` | `7.x` | `8.x` |
| --- | --- | --- | --- | --- |
| Requests | Y | Y | Y | Y |
| Errors | Y | Y | Y | Y |
| Timeouts | Y | Y | Y | Y |
| AvgRequestsPerSecond | Y | Y |  |  |
| 5minRateReqsPerSecond | Y |  |  |  |
| 5minRateRequestsPerSecond |  | Y |  |  |
| 15minRateReqsPerSecond | Y |  |  |  |
| 15minRateRequestsPerSecond |  | Y |  |  |
| AvgTimePerRequest | Y | Y |  |  |
| MedianRequestTime | Y | Y |  |  |
| 75thPcRequestTime | Y | Y |  |  |
| 95thPcRequestTime | Y | Y |  |  |
| 99thPcRequestTime | Y | Y |  |  |
| 999thPcRequestTime | Y | Y |  |  |
| ClientErrors |  |  | Y | Y |
| ServerErrors |  |  | Y | Y |
| …

[solr] Add version 7.x and 8.x support

---

mackerel-plugin-solr/lib/solr.go

Hello,
I found that several metrics values are cumulative in Apache Solr. So they are needed to specify the option `Diff: true`.

[solr] Fix several graph definitions

---

mackerel-plugin-varnish/lib/varnish.go

If varnish persists communication with the upstream, the values of backend_reuse and backend_recycle also change.
- [Reusing backend connections to increase performance](https://www.fastly.com/blog/reusing-backend-connections-increase-performance)
- > What you're looking for is for backend_reuse to not be zero, and ideally to be an order of magnitude, or more, higher than backend_conn. 
- [Enormous amount of connections stuck in CLOSE_WAIT state with Varnish](https://stackoverflow.com/questions/27247756/enormous-amount-of-connections-stuck-in-close-wait-state-with-varnish)
- > And finally, check the output of varnishstat -1 |grep backend to see if varnish is able to reuse backend connections (backend_reuse) and if it has noticed that they are closed (backend_toolate). The values should be …

[varnish] Added backend_reuse and backend_recycle metrics

---

mackerel-plugin-varnish/lib/varnish.go

Some objects are stored in *Transient storage* separately from normal cached objects.
This allows you to see how much memory Varnish is using for its cache.
- https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html#transient-storage
- > If you name any of your storage backend "Transient" it will be used for transient (short lived) objects. This includes the temporary objects created when returning a synthetic object. By default Varnish would use an unlimited malloc backend for this.
- Depending on the value of Transient storage, it may cause a memory leak.

[varnish] Added metrics for Transient storage

---

mackerel-plugin-varnish/lib/varnish.go

I guess this statement had used for debugging.

[varnish] remove unnecessary printf

---

Makefile

This PR will modify `make testconvention`.
The PRs created by Dependabot sometimes breaks the CI because the CI processes may update **go.\*** files automatically. ex: #619
`make testconvention` checks whether there is the diffs or not. This behavior purposes in checking to need to run `go generate`. Therefore it is not needed to know that **go.\*** files was changed in CI processes.
This code was tested on #625

ignore diffs of go.mod and go.sum

---

go.mod
go.sum

<del>Current(2020/06/04) latest</del>
<ins>Now (2020/06/04) the latest version is 1.31.11</ins>

Update aws-sdk-go to 1.31.11

---

mackerel-plugin-mysql/lib/mysql.go

mackerel-plugin-mysql was mistakenly sending bytes/min as Bytes_sent and Bytes_received.  This PR fixes this problem to send bytes/sec as Bytes_sent and Bytes_received.

[plugin-mysql] Fix to send Bytes_sent and Bytes_received correctly

---

mackerel-plugin-linux/lib/linux.go
mackerel-plugin-linux/lib/linux_test.go

ref: #655
As reported at #655, Linux Kkrnel 4.18+ has 11+ fields in `/sys/block/*/stat` and mackerel-plugin-linux did not consider such cases.
Easiest way to testing with macOS is using Docker for Mac, since its linuxkit has kernel 4.19. (Note that this behavior depends kernel version, not Docker image's Linux distribution version.)
```
[github.com/mackerelio/mackerel-agent-plugins/mackerel-plugin-linux]$ docker run --rm -it -v $(PWD):/app debian:buster
root@d97d5092b97e:/# uname -a
Linux d97d5092b97e 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
root@d97d5092b97e:/# /app/mackerel-plugin-linux
2020/07/27 14:14:57 interrupts does not exist at last fetch
2020/07/27 14:14:57 context_switches does not exist at last fetch
2020/07/27 14:14:57 forks does not exist at last …
```

[plugin-linux] Do not skip diskstat metrics with Linux kernel 4.18+

---

.travis.yml
Makefile
packaging/deb-v2/debian/control
packaging/rpm/mackerel-agent-plugins-v2.spec
packaging/rpm/mackerel-agent-plugins.spec

I added recipes to make the packages for arm64 architecture, and fixed Architecture of deb to be correct.
see mackerelio/mkr#310

add arm64 architecture packages, and fix Architecture field of deb

---

mackerel-plugin-plack/lib/plack.go
mackerel-plugin-plack/lib/plack_test.go

I encountered responses as below from Plack::Middleware::ServerStatus::Lite 0.36 & Perl 5.32.
The responses include xxxKbytes and xxxWorkers values encoded as a JSON number, not a string.
```json
{
"TotalKbytes": 0,
"BusyWorkers": 1,
"stats": [],
"TotalAccesses": 3,
"IdleWorkers": 4,
"Uptime": "1607091099"
}
```
This PR enables to parse numbers and strings both in the responses.

Enables to parse responses which include string and number from Plack.

---

go.mod
go.sum
mackerel-plugin-redis/lib/redis_test.go

garyburd/redigo was moved to gomodule/redigo.
see https://github.com/garyburd/redigo

migrate garyburd/redigo -> gomodule/redigo

---

mackerel-plugin-mysql/lib/mysql.go

Label names of `innodb_tables_in_use` and `innodb_locked_tables` seems to be the opposite.

Fix labels of innodb_tables_in_use and innodb_locked_tables

---

Makefile
tool/create-release-pullrequest

`release` target is still used for our internal releasing tool.

Revert "delete unused Makefile tasks"

---

go.mod
go.sum
mackerel-plugin-aws-ses/README.md
mackerel-plugin-aws-ses/lib/aws-ses.go
mackerel-plugin-aws-ses/lib/aws-ses_test.go

- migrate from goamz, go-ses to aws-sdk-go
- `--endpoint`, is changed to the deprecated
- `--region` took the place of  `--endpoint`

migrate from goamz,go-ses to aws-sdk-go

---

mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-fluentd/lib/fluentd_test.go

fluentd 1.6 has extended metrics by monitor-agent.
https://www.fluentd.org/blog/fluentd-v1.6.0-has-been-released
This PR enables to fetch these extended metrics with the `-extended_metrics` option.
Why fetch to extended metrics is optional, these metrics are too many if it not needed (for pricing impact).
```
Usage of mackerel-plugin-fluentd:
-extended_metrics string
extended metric names joind with ',' or 'all' (fluentd >= v1.6.0)
```
-extended_metrics accepts extended metric names joined with `,`.
```console
$ mackerel-plugin-fluentd -extended_metrics emit_records,emit_count
fluentd.retry_count.xxx	0.000000	1614968838
fluentd.buffer_queue_length.xxx	0.000000	1614968838
fluentd.buffer_total_queued_size.xxx	0.000000	1614968838
fluentd.emit_records.xxxx	0.000000	1614968838 …
```

Support to extended metrics for fluentd 1.6.

---

go.mod
go.sum

Today we tagged new versions of go-mackerel-plugin(-helper).
Since this repo refers those repos by pseudo-versions, I'd like to refer them as proper versions.

Use latest go-mackerel-plugin(-helper)

---

Makefile
mackerel-plugin-accesslog/test.sh
mackerel-plugin-apache2/test.sh
mackerel-plugin-docker/test.sh
mackerel-plugin-mongodb/test.sh
mackerel-plugin-mysql/test.sh
mackerel-plugin-openldap/test.sh
mackerel-plugin-postgres/test.sh
mackerel-plugin-redis/test.sh
test.bash

I changed workflow to run tests (**&lt;plugin&gt;/test.sh**) for each plugins.
The "make cover test" task ends up with the reports of each tests of the plugin.
```
OK: mackerel-plugin-accesslog/test.sh
OK: mackerel-plugin-apache2/test.sh
OK: mackerel-plugin-docker/test.sh
OK: mackerel-plugin-mongodb/test.sh
OK: mackerel-plugin-mysql/test.sh
OK: mackerel-plugin-openldap/test.sh
OK: mackerel-plugin-postgres/test.sh
OK: mackerel-plugin-redis/test.sh
```

[ci] run tests on the workflow

---

mackerel-plugin-redis/lib/redis.go
mackerel-plugin-redis/test.sh

You would be able to look **"saveValues:  json: unsupported value: +Inf"** error  in the result of GitHub Action's output of the first commit of this PR; [756ca59](https://github.com/mackerelio/mackerel-agent-plugins/pull/779/checks?check_run_id=2915016825)
Therefore I fixed it.
see #770

[plugin-redis] avoid to store +Inf

---

mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-fluentd/lib/fluentd_test.go

add metric-key-prefix option of fluentd plugin.
```sh
$ ./mackerel-plugin-fluentd --help 2>&1 | grep prefix
-metric-key-prefix string
Metric key prefix (default "fluentd")
```

[fluentd] add metric-key-prefix option.

---

.github/workflows/create-release-pr.yml
tool/update-docs.pl

We are using [Mackerel::ReleaseUtils](https://metacpan.org/pod/Mackerel::ReleaseUtils) in the version update process and want to replace it.
In this pull request, I'm writing the code to try the replacement.
This GitHub Action does not actually work, but runs in "dry-run" mode.

Replacing the version update process

---

mackerel-plugin-fluentd/README.md
mackerel-plugin-fluentd/lib/fluentd.go
mackerel-plugin-fluentd/lib/fluentd_test.go

add workers option of fluentd plugin.
workers option supports fetching metrics for multi process workers.
refs.
- [Multi Process Workers - Fluentd]( https://docs.fluentd.org/deployment/multi-process-workers )
- [monitor_agent - Fluentd]( https://docs.fluentd.org/input/monitor_agent#multi-process-environment )

[fluentd] add workers option.

---

.github/workflows/test.yml
README.md
mackerel-plugin-accesslog/lib/accesslog.go
mackerel-plugin-accesslog/lib/accesslog_test.go
test.bash

It is not good to use ioutil.ReadAll to skip all logs.
ioutil.ReadAll reads all bytes into memory, so if the access log is large then the plugin might be OOM crash.

[accesslog] use Seek to skip the log

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

There is a difference in the values that can be obtained depending on the mysql version.
Followed the previous implementation to retrieve values, but changed the labels to avoid confusion because different values are organized with similar names.
Also, the values that were failing to be retrieved are now retrieved.

added "pending log flushes"

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

some definitions have been added in duplicate in the past. They cannot be removed to ensure compatibility.
I have been added comments for clarity understand.

[nit] added comments for duplicate graphdefs.

---

mackerel-plugin-postgres/lib/postgres.go

When wal_level is not set to `logical`, suppress  fetchXlogLocation to avoid error.
On AWS RDS Aurora PostgreSQL,
`SELECT pg_is_in_recovery()` returns `f` but wal_level is `replica`
```console
$ psql -U XXX -h XXX.XXX.ap-northeast-1.rds.amazonaws.com -c "SELECT pg_is_in_recovery()"
...
pg_is_in_recovery
-------------------
f
(1 row)
$ psql -U XXX -h XXX.XXX.ap-northeast-1.rds.amazonaws.com -c "SELECT setting FROM pg_settings WHERE name = 'wal_level'"
...
setting
---------
replica
(1 row)
```
To run `SELECT pg_wal_lsn_diff(pg_current_wal_lsn(), '0/0')` successfully,
wal_level must be `logical`.
```console
$ mackerel-plugin-postgres -hostname XXX.XXX.ap-northeast-1.rds.amazonaws.com -database XXX -user XXX -password XXX
2021/08/17 11:14:02 ERROR <metrics.plugin.postgres> Failed to select …
```

[plugin-postgres] suppress fetchXlogLocation when wal_level != 'logical'

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

Starting with mysql5.7, the metric for "RW-sx" is displayed. I want to observe this.
- Added according to examples such as "RW-shared".
- Correct the test and make sure it passes.
- I have not confirmed the behavior in MySQL8.0.
- Starting with mysql5.7.8, The "Mutex spin waits" line is no longer displayed.
- https://github.com/mysql/mysql-server/commit/3574d439c1cf7ad39a5077d5d3c7ff5ad835a882
- https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-8.html

[mysql] adapt for mysql5.7's InnoDB SEMAPHORES metrics

---

go.mod
go.sum
mackerel-plugin-snmp/lib/snmp.go

alouca/gosnmp has not been updated for a long time.
changed to use a successor library.

replace library gosnmp in mackerel-plugin-snmp

---

go.mod
go.sum
mackerel-plugin-redis/lib/redis.go

The redis client library `fzzy/radix` seems to be removed, so I migrated the library to `gomodule/redigo`.

[plugin-redis] migrate redis client library to redigo

---

mackerel-plugin-sidekiq/README.md
mackerel-plugin-sidekiq/lib/sidekiq.go
mackerel-plugin-sidekiq/lib/sidekiq_test.go

Measures the difference between when the oldest job was pushed into the queue and the current time as latency.
ref: https://github.com/mperham/sidekiq/wiki/Monitoring#monitoring-queue-latency
I refered the following code for implementation.
https://github.com/mperham/sidekiq/blob/46f4c6bd9ee0b2f5502a1dc0d03414989ad65063/lib/sidekiq/api.rb#L240-L254

[plugin-sidekiq] add queue latency metric

---

mackerel-plugin-linux/lib/linux.go

ログインしているユーザが 0 の場合に linux.users メトリックに 0 が投稿されない問題の修正です。
ログインしているユーザが 0 の場合 `(*p)["users"] = 0` で 0 を代入していますが、最後にメトリックを出力する以下の処理で int 型に対応しておらずメトリックが投稿されないため、float64 で代入しています。
https://github.com/mackerelio/go-mackerel-plugin-helper/blob/3d9512468e0b00efe5bc2189eead8b4275fd8e9d/mackerel-plugin.go#L87

[linux] users メトリックに 0 が投稿されない問題を修正

---

.github/workflows/test.yml

shogo82148/actions-goveralls now deplicates `job-number` input ( https://github.com/shogo82148/actions-goveralls/commit/883ba99002413b1b1a998431af467d00628c3f46 ). It say "Input 'job-number' has been deprecated with message: use flag-name instead".
Example notification : https://github.com/mackerelio/mackerel-agent-plugins/actions/runs/2165034703 <img width="641" alt="スクリーンショット 2022-04-14 13 10 01" src="https://user-images.githubusercontent.com/452772/163312079-0a532c26-a4c8-401b-aa7c-47c4ee4ee2ee.png">
```yaml
job-number:
description: "job number (DEPRECATED)"
required: false
default: '${{ strategy.job-index }}'
deprecationMessage: "use flag-name instead"
```
```yaml
flag-name:
description: 'Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.' …
```

Fix: Input 'job-number' has been deprecated with message: use flag-name instead

---

mackerel-plugin-mysql/lib/mysql.go
mackerel-plugin-mysql/lib/mysql_test.go

Amazon Aurora could return aio statistics like below:
```
Pending normal aio reads:, aio writes: [0, 0, 0, 0] ,
```
That statistics is missing values of reads so plugin-mysql panics when parsing aio line.

[plugin-mysql] fix panic when parsing aio stats

---

mackerel-plugin-docker/lib/docker.go

In the past, Docker 1.5.x or earlier didn't have APIs to retrieve metrics so *plugin-docker* was read any metrics from files.
Today, that behavior still be supported if `-method File` option are passed to *plugin-docker* command.
However I think we could stop to support that option because Docker 1.6 had been released in 2015 and it is already marked as EOL.
This PR deletes `-method File` related codes and makes to print a message and exit if `-method File` is passed.

[plugin-docker] (Breaking) drop 'File' method support

---

mackerel-plugin-docker/lib/docker.go
mackerel-plugin-docker/lib/docker_test.go

Fix #885
Fix the issue `mackerel-plugin-docker` always outputs zero value CPU/Memory metrics for Docker host with cgroup v2.
(The issue filed in https://github.com/mackerelio/mackerel-agent-plugins/issues/885)
In particular, make the following metrics proper value on cgroupv2 host.
- `docker.cpuacct_percentage.<container_name>.user`
- `docker.cpuacct_percentage.<container_name>.system`
- `docker.memory.<container_name>.cache`
- `docker.memory.<container_name>.rss`
It is because the output of Docker Stats API on cgroupv2 host differs from the one on cgroup host.
> On a cgroup v2 host, the following fields are not set
>
> blkio_stats: all fields other than io_service_bytes_recursive
> cpu_stats: cpu_usage.percpu_usage
> memory_stats: max_usage and failcnt Also, memory_stats.stats fields are …

[plugin-docker] fix CPU/Memory metrics on Docker hosts uses cgroup2

---

mackerel-plugin-aws-ec2-ebs/README.md
mackerel-plugin-aws-ec2-ebs/lib/aws-ec2-ebs.go

I fixed period-misuse bugs in **mackerel-plugin-aws-ec2-ebs**.
The plugin retrieves recent values of  the metrics each minutes, and then it elects only a most recent value each metrics from them. Thus these metric values are aggregated by a minute.
In addition, some metric's graph definition such as `ec2.ebs.bandwidth.#.read` or `ec2.ebs.throughput.#.read` are designed with per-second units. Thus the plugin should convert these `Sum`ed values to the values avarage per second, like `val / 60`.
https://github.com/mackerelio/mackerel-agent-plugins/blob/1be28e2aed5f8ca05cf8b2ee35717283405c722b/mackerel-plugin-aws-ec2-ebs/lib/aws-ec2-ebs.go#L230-L243
However, in the current implementaton, that formula is wrong.
For instance, *getLastPoint* method returns a metric value and its period that are …

[plugin-aws-ec2-ebs] fix misuse of period

---

mackerel-plugin-aws-ec2-ebs/lib/aws-ec2-ebs.go

fix calcurate procedure
see. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html

[aws-ec2-ebs] fix calcurate procedure of Nitro instance

---

mackerel-plugin-mongodb/lib/mongodb.go
mackerel-plugin-mongodb/lib/mongodb_test.go

The metric-key-prefix option has been added to mackerel-plugin-mongodb to resolve issues that have been inquired to support.
In line with this, the graph labels now also reflect the prefix.

[mongodb] add metric-key-prefix option

---

mackerel-plugin-elasticsearch/lib/elasticsearch.go
mackerel-plugin-elasticsearch/lib/elasticsearch_test.go
mackerel-plugin-elasticsearch/lib/stat.json

Hi.
I resolved some problems in mackerel-plugin-elasticsearch.
Added `-insecure`,`-user`, and `-password` flags.
Elastcsearch(ES) v8.5 official docker image runs on https with self-signed certificates and requires Basic authentication.
> docker run -p 9200:9200 -e "ELASTIC_PASSWORD=pass" -e "discovery.type=single-node" elasticsearch:8.5.0
This command runs the HTTPS server on port 9200, and basic auth 'elastic:pass' is required.
Recent ES versions no longer serve some stats values that are expected by this plugin.
For example, for ES v8.5.0, many errors occurred, as below.
```
<metrics.plugin.elasticsearch> Failed to find 'filter_cache_size': Cannot handle as a hash
<metrics.plugin.elasticsearch> Failed to find 'evictions_filter_cache': Cannot handle as a hash …
```

Fix Elasticsearch plugin.

---

mackerel-plugin-elasticsearch/test.sh
tool/waituntil.bash

I saw the test was sometimes failed because elasticsearch container do not become running state even if test script sleeps a minute.

[plugin-elasticsearch] Fix the test for elasticsearch

---

.github/workflows/test.yml
packaging/deb-v2/debian/rules
packaging/deb/debian/rules

- The plugins packages builds on **ubuntu-latest** label
- Now, **ubuntu-latest** label points to **ubuntu-22.04**
- **ubuntu-22.04** switches to **zst** as default format of deb package
We provides deb packages to many OSes so we should keep **xz** format to compress format of the packages.

packaging: make compression format xz

---

Makefile

The environment ubuntu-latest for GitHub Actions is ubuntu 22.04.
It turns out that glibc is new and the built binary compatibility is broken in some environments.
So We made a change to build with CGO_ENABLED=0

added compile option.

---

.github/dependabot.yml
Makefile

- This repository has multiple go.mod files.
- mackerel-plugin-mysql has an independent go.mod
- rpm-v1, deb-v1 task on Makefile creates individual compiled binaries.

fix build on current working directory.

---

.github/dependabot.yml
.github/workflows/create-release-pr.yml
.github/workflows/test.yml

This repository's workflows look antiquated. Deprecated features and runtimes of Github Actions will soon be unavailable.
So we activate dependabot for GitHub Actions to automate updates.

Enables Dependabot version updates for GitHub Actions

---

mackerel-plugin-php-apc/README.md
mackerel-plugin-php-apc/lib/php-apc.php

In APCu + PHP>=7 environments, `apc_cache_info` methods are no longer support.
The PR fix it and support APCu extention without shim.
PHP8やPHP7+APCuでは正しく動作しなかったため、修正するPRとなります。
もはやPHP7はEOLですが、それ以降のPHP8+APCuでも本対応が必要です。
Goで書かれた箇所は変更しておらず、APC(APCu)の統計情報を取得するPHPスクリプトのみの修正です。
`apc_*` 関数を `apcu_*` 関数に書き換えています。
> 「APCプラグインなのにAPCuサポートをするのか？」という点は後述します
本PRのコードで正常に取得できる様子
```
$ curl http://127.0.0.1:1234/mackerel/php-apcu.php // ファイル名は区別のためPRと変更してあります
memory_segments:1
segment_size:33554312
total_memory:33554312
cached_files_count:1
cached_files_size:128
cache_hits:16
cache_misses:7
cache_full_count:0
user_cache_vars_count:1
user_cache_vars_size:128
user_cache_hits:16
user_cache_misses:7
user_cache_full_count:0
```
既存コードで500が返る様子(修正したい問題です)
```
$ curl -v http://127.0.0.1:1234/mackerel/php-apc.php // …
```

Fix support APCu and PHP7 or later environment.

---

mackerel-plugin-twemproxy/lib/twemproxy.go

In mackerel-plugin-twemproxy, `Server Timeout` and `Server Error` are reversed in the display label and value set.
This patch trys to fix it.

Fix timeout/error labels of mackerel-plugin-twemproxy

---

mackerel-plugin-fluentd/README.md

I found an option that was added in #738 but it is not described in the README.

[fluentd] add README.md with extended_metrics option

---

mackerel-plugin-docker/lib/docker.go
mackerel-plugin-docker/lib/docker_test.go

`docker.cpuacct_percentage.*.{user,system}` metrics observed after restarting a docker container appear to be an unusually high spike.
This problem is due to the fact that the comparison of two uint values is made by subtraction.
https://github.com/mackerelio/mackerel-agent-plugins/blob/cbd69a9fe7e468d1fe193e5cffbde2f3cdc2a5ce/mackerel-plugin-docker/lib/docker.go#L273-L276
This pull request enables to correctly detect that counters have been reset and also set metrics to moderate values in that case.
You can see that `docker.cpuacct_percentage.hoge_2e3173.{user,system}` metrics have huge values after executing `docker restart` command.
```console
$ ./build/darwin/arm64/mackerel-plugin-docker
docker.memory.hoge_2e3173.cache	11956224	1692718764
docker.memory.hoge_2e3173.rss	3805184 …
```

Fixed Docker CPU Percentage's unusual spike when restarting containers

---

mackerel-plugin-redis/README.md
mackerel-plugin-redis/lib/redis.go

our customers needed TLS support at Redis datastore on some managed cloud services.

added TLS support on mackerel-plugin-redis

---

.github/workflows/test.yml

I updated go toolchain
- build: go 1.22
- test: go 1.21, 1.22 (workflows)
- ref https://github.com/mackerelio/workflows/blob/4ff6e7b3422ff5f9d078848d32b1a48850ad3f8d/.github/workflows/go-test.yml#L15
- lint: go 1.22

update go version -> 1.22

---

go.mod
go.sum
mackerel-plugin-windows-server-sessions/README.md
mackerel-plugin-windows-server-sessions/lib/sessions.go
mackerel-plugin-windows-server-sessions/lib/sessions_other.go

WMIC is deprecated as of the 21H1 semi-annual channel release of Windows Server. cf.) https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic
So, I have updated mackerel-plugin-windows-server-sessions to use a Go library that interact directly with WMI instead of WMIC command.
```console
> WMIC PATH Win32_PerfFormattedData_PerfNet_Server GET ServerSessions /FORMAT:CSV
Node,ServerSessions
EC2AMAZ-BAJQD2D,0
```
```console
> cd mackerel-plugin-windows-server-sessions
> go run ./main
windows.server.sessions.EC2AMAZ-BAJQD2D.count   0       1709118187
```
```console
> go run ./main
windows.server.sessions.EC2AMAZ-BAJQD2D.count   0       1709127711
```

[mackerel-plugin-windows-server-sessions] Remove the dependency for WMIC command

---

mackerel-plugin-redis/README.md
mackerel-plugin-redis/lib/redis.go

The mackerel-plugin-redis plugin allows you to specify username.
If nothing is set, it will be the default user.

Allow mackerel-plugin-redis to specify username

---

mackerel-plugin-snmp/lib/snmp.go
mackerel-plugin-snmp/rule.txt
mackerel-plugin-snmp/test.sh
mackerel-plugin-snmp/testdata/snmpd.conf

I found mackerel-plugin-snmp failed to parse a number of STRING type from SNMP device, like `strconv.ParseFloat: parsing "[51 46 49 52]": invalid syntax`.
For example, original value from SNMP device is '3.14', and `51 46 49 52` seems the byte array of '3.14'.
Because it is usually impossible to change a type on the SNMP device side, the receiver has a responsiblity to accept it.
Here is a patch to support STRING number.
- `parseFloat` again for byte array with forcing String conversion by `fmt.Sprintf('%s'` only if the parsing failed first. `resp.Variables[0].Value` may be vary, so original first `fmt.Sprint(resp.Variables[0].Value)` works well, except a byte array of string.
- To test it, extend command is added. It will back STRING 3.14. `.1.3.6.1.4.1.8072.1.3.2.3.1.2.4.101.99.104.111 …

add STRING number support

---

mackerel-plugin-mailq/lib/fixtures/postqueue
mackerel-plugin-mailq/lib/main.go
mackerel-plugin-mailq/lib/main_test.go

Fixes #1185 
This PR fixes the mail queue count regexp capture for Postfix when there's only 1 item in the mail queue.
**Note/Update**: The tests in the package modified are passing as I've tested them locally.

[plugin-mailq] mailq/postfix: Fix mail queue count regexp capture when it's `1`

---

mackerel-plugin-php-fpm/lib/php-fpm.go

`slow_requests` metric is counter. cf.) https://www.php.net/manual/en/fpm.status.php#:~:text=The%20total%20number%20of%20requests%20that%20have%20hit%20the%20configured%20request_slowlog_timeout.
In monitoring, we are often more interested in the increment than in the raw slow requests number. So, I added a slow_requests_delta metric that outputs the difference values of slow_requests.
```console
$ sudo ./mackerel-plugin-php-fpm -socket /var/run/php/php-fpm.sock
php-fpm.processes.total_processes	2	1719783877
php-fpm.processes.active_processes	1	1719783877
php-fpm.processes.idle_processes	1	1719783877
php-fpm.max_active_processes.max_active_processes	1	1719783877
php-fpm.max_children_reached.max_children_reached	0	1719783877
php-fpm.queue.listen_queue	0	1719783877 …
```

[mackerel-plugin-php-fpm] add slow_requests_delta metrics because slow_requests is a counter

---

mackerel-plugin-aws-ec2-ebs/README.md

I've been setting up mackerel agent with aws-ec2-ebs plugin according to README, and was faced with insufficient AWS IAM policy attachment.
I've recieved two error messages (several ids are masked) and now it turned out that two essential actions (`ec2:DescribeInstanceTypes` and `ec2:DescribeInstances`) are not mentioned on README for aws-ec2-ebs plugin. So this PR fixes it.
```
Aug 28 07:48:10 ip-10-0-0-100 mackerel-agent[409653]: 2024/08/28 07:48:10 INFO <metrics.plugin> command mackerel-plugin-aws-ec2-ebs outputted to STDERR: "2024/08/28 07:48:10 UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::123456789012:assumed-role/my-role/i-01234567890abcdef is not authorized to perform: ec2:DescribeInstanceTypes because no identity-based policy allows …
```

[plugin-aws-ec2-ebs] add actions to README need to be allowed in the iam policy

---

mackerel-plugin-jvm/README.md
mackerel-plugin-jvm/lib/jvm.go
mackerel-plugin-jvm/lib/jvm_test.go

The mackerel-plugin-jvm monitors the application specified in --javaname, but there is an issue that it can only monitor one of the applications if there are multiple applications with the same name. I would like to solve this issue by making it possible to use --metric-key-prefix and --metric-label-prefix.
```
jvm.tomcat-ex.new_space.NGCMX	1025507328.000000	1731999116
jvm.tomcat-ex.new_space.NGC	35651584.000000	1731999116
jvm.tomcat-ex.new_space.EU	18874368.000000	1731999116
jvm.tomcat-ex.new_space.S0U	0.000000	1731999116
jvm.tomcat-ex.new_space.S1U	4194304.000000	1731999116
jvm.tomcat-ex.old_space.OGCMX	1025507328.000000	1731999116
jvm.tomcat-ex.old_space.OGC	31457280.000000	1731999116
jvm.tomcat-ex.old_space.OU	5605888.000000	1731999116
jvm.tomcat-ex.metaspace.MCMX	1140850688.000000 …
```

[jvm] add prefix option

---

.github/workflows/test.yml

The CI for the master branch is failing due to the absence of the `build-essential:native` package, as seen in [this run](https://github.com/mackerelio/mackerel-agent-plugins/actions/runs/12500547540/job/34876951429). It appears that the cause is the change to Ubuntu 24.04, as the runner is specified to use ubuntu-latest in GHA.
This pull request specifies the runner to use ubuntu-22.04.

Fix CI build

---

mackerel-plugin-php-fpm/lib/php-fpm.go
mackerel-plugin-php-fpm/lib/php-fpm_test.go

PHP 8.4 introduces new field `memory peak` for php-fpm status page.
https://github.com/php/php-src/blob/0454901ed1518cfb42bc77ac91728591b58c3e6e/UPGRADING#L339
The memory usage peak since FPM started.
This PR subjects to add new metric and graph def to support it on mackerel-plugin-php-fpm plugin.
Since memory peak does not fit into the existing PHP-FPM plugin graph definition, I have added a new one.
Max Active Processes is a similar graph that keeps the peaks since PHP-FPM was started, so I used that as a reference. However, I changed the units to bytes.
To avoid creating meaningless graphs in versions older than PHP 8.4, I have coded to not send out a metric when the value of a field cannot be retrieved (=0).
This would mean that the graph would not be generated even when it was really …

support memory peak value which is introduced in PHP 8.4 on mackerel-plugin-php-fpm

---

.github/workflows/test.yml
Makefile
packaging/tar/build.sh

Hi. This PR adds support for building tar.gz release packages.
We want to use the plain tar.gz packages instead of rpm or deb, similar to the mackerel-agent provided.
`make tar` builds tar.gz for release packages.

Add tar.gz packaging

---

.github/workflows/test.yml
.gitignore
Makefile
mackerel-plugin.go

- Go 1.24 or above, can read package version from [BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo)
- also can use vcs.revision
- therefore we can remove build option `-X main.gitcommit`

git commit, version from runtime/debug
